#!/usr/bin/env python3
"""Rewrite a Renode script's app-image patch addresses for a moved layout.

    python3 abi/sim_patches.py machine.resc out/machine-moved.resc

The rig patches a handful of instructions in the application image before it
runs (machine.resc's `imagePatches`), by absolute address. Those addresses are
the app's old ones, so a layout that moves the text has to move the patches with
it or the run patches whatever landed there instead. The move map
(out/relink-place-moves.json, written by abi/blobify.py) is the same one the
stale-address scan uses.

An address the map does not move is left alone, which is what the MBR and
SoftDevice patches need; an address inside a moved section is translated, and an
address in the app image that no section covers is an error rather than a guess.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIM = os.path.dirname(HERE)
APP_BASE = 0x27000
APP_END = 0xF117C

# The four ways the rig names an address in the application image: a memory
# patch, a hook on an instruction, a monitor variable holding one, and a
# peripheral property in the platform description -- the WPP pipe takes the
# three app addresses it hooks that way.
SITE = re.compile(r"((?:sysbus\s+Write(?:Byte|Word|DoubleWord)|cpu\s+AddHook)\s+"
                  r"|\$\w+\??=|^\s*\w+:\s+)0x([0-9a-fA-F]+)\b", re.MULTILINE)


def translate(moves):
    """address -> address, for the app image only."""
    ranges = sorted((m["old"], m["end"], m["new"]) for m in moves)

    def at(addr):
        if not APP_BASE <= addr < APP_END:
            return addr
        lo, hi = 0, len(ranges)
        while lo < hi:
            mid = (lo + hi) // 2
            if ranges[mid][0] <= addr:
                lo = mid + 1
            else:
                hi = mid
        if lo and ranges[lo - 1][1] > addr:
            return ranges[lo - 1][2] + addr - ranges[lo - 1][0]
        # Data does not move in this layout, so an address in a section that
        # stayed is already right.
        return addr
    return at


def macro_only(lines, name):
    """Just `macro NAME """ + '"""' + """...""" + '"""' + """` out of a Renode script."""
    out, inside = [], False
    for line in lines:
        if line.strip() == "macro " + name:
            inside = True
        if inside:
            out.append(line)
            if len(out) > 2 and line.strip() == '"""':
                return out
    sys.exit("%s defines no macro %s" % (name, name))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("target")
    ap.add_argument("--macro", metavar="NAME",
                    help="emit only this macro's definition from the source,"
                         " which is how the update run gets the patches for the"
                         " image that is running after the update while the one"
                         " it started from keeps the original addresses")
    ap.add_argument("--moves", default=os.path.join(SIM, "out", "relink-place-moves.json"))
    args = ap.parse_args()

    with open(args.moves) as fh:
        moves = json.load(fh)
    if not moves:
        sys.exit("%s is empty: nothing moved, so there is nothing to rewrite"
                 % args.moves)
    at = translate(moves)

    moved = []

    def rewrite(m):
        old = int(m.group(2), 16)
        new = at(old)
        if new != old:
            moved.append((old, new))
        return "%s0x%x" % (m.group(1), new)

    with open(args.source) as fh:
        lines = fh.readlines()
    # The `:name:`/`:description:` block has to stay at the top of a .resc, so
    # the note about where the file came from goes after it.
    head = 0
    while head < len(lines) and (lines[head].startswith(":")
                                 or lines[head].startswith(":  ")):
        head += 1
    note = ["// " if args.source.endswith(".repl") else "# ",
            "Generated by abi/sim_patches.py from %s, do not edit.\n"
            % os.path.basename(args.source)]
    note = ["".join(note)]
    body = lines[head:]
    if args.macro:
        body = macro_only(body, args.macro)
    with open(args.target, "w") as fh:
        fh.write(SITE.sub(rewrite, "".join(note + body)))
    print("%s: %d patch addresses moved" % (args.target, len(moved)))
    for old, new in moved:
        print("  0x%x -> 0x%x" % (old, new))


if __name__ == "__main__":
    main()
