/* HWA10 (ScanWatch 2) application firmware v3411: the WPP wire.
 *
 * Generated by abi/protocol.py from the image's own codec bodies; do
 * not edit. What each of these is, not where it is: abi/symbols.yaml
 * holds the addresses. */
#ifndef WITHINGS_WPP_OBJECTS_H
#define WITHINGS_WPP_OBJECTS_H

#include "withings/wpp.h"

/* WPP object type 256 (Null), 0 bytes; encoder 0x9917a; encoder 0x9a918;
   parser 0x4ed90.
   */
struct wpp_Null {
};

/* WPP object type 263 (BatteryPercent), 2 bytes; encoder 0x99216
   (+0x0@0x99236).
   */
struct wpp_BatteryPercent {
    unsigned short percent;
};

/* WPP object type 272 (Cmderror), 8 bytes; encoder 0x9923a (+0x0@0x99256
   +0x4@0x99262); parser 0x4edb0 (+0x0@0x4edbc +0x4@0x4edc4).
   */
struct wpp_Cmderror {
    unsigned short cmd;
    unsigned char pad_2[0x2];
    unsigned int err;
};

/* WPP object type 278 (StoredMeasureMeta), 28 bytes; encoder 0x99266
   (+0x0@0x99282 +0x4@0x9928a +0x8@0x99296 +0x14@0x9929e +0x18@0x992aa).
   */
struct wpp_StoredMeasureMeta {
    unsigned int uid;
    unsigned char user_id_cnt;
    unsigned char pad_5[0x3];
    unsigned int user_id[0x3];
    unsigned char attrib;
    unsigned char pad_15[0x3];
    unsigned int time;
};

/* WPP object type 279 (StoredMeasureData), 8 bytes; encoder 0x992ae
   (+0x0@0x992ca +0x4@0x992d2 +0x6@0x992e0).
   */
struct wpp_StoredMeasureData {
    unsigned int value;
    unsigned short type;
    short exponent;
};

/* WPP object type 280 (ConnectReason), 2 bytes; encoder 0x992e4
   (+0x0@0x99304).
   */
struct wpp_ConnectReason {
    unsigned short reason;
};

/* WPP object type 281 (UserUnit), 6 bytes; encoder 0x99308 (+0x0@0x99324
   +0x1@0x9932e +0x2@0x99336 +0x4@0x99342).
   */
struct wpp_UserUnit {
    unsigned char cmd;
    signed char rc;
    unsigned short type;
    unsigned short unit;
};

/* WPP object type 285 (DebugDumpData), 65 bytes; encoder 0x99346
   (+0x0@0x99368).
   */
struct wpp_DebugDumpData {
    unsigned char buf[0x41];
};

/* WPP object type 286 (DebugDumpMask), 4 bytes; parser 0x4ee88
   (+0x0@0x4ee90).
   */
struct wpp_DebugDumpMask {
    unsigned int mask;
};

/* WPP object type 287 (DebugDumpType), 8 bytes; encoder 0x9936c
   (+0x0@0x99388 +0x4@0x99394).
   */
struct wpp_DebugDumpType {
    unsigned int type;
    unsigned int size;
};

/* WPP object type 289 (LocaleSet), 65 bytes; encoder 0x99398
   (+0x0@0x993ba).
   */
struct wpp_LocaleSet {
    unsigned char locale[0x41];
};

/* WPP object type 290 (ProbeChallenge), 130 bytes; encoder 0x993be
   (+0x0@0x993e2 +0x41@0x993f0); parser 0x4eee4 (+0x0@0x4eeee
   +0x41@0x4eef8).
   */
struct wpp_ProbeChallenge {
    unsigned char mac[0x41];
    unsigned char challenge[0x41];
};

/* WPP object type 291 (ProbeChallengeResponse), 65 bytes; encoder 0x993f4
   (+0x0@0x99416); parser 0x4ef24 (+0x0@0x4ef2c).
   */
struct wpp_ProbeChallengeResponse {
    unsigned char answer[0x41];
};

/* WPP object type 292 (BatteryVoltageMv), 2 bytes; encoder 0x9941a
   (+0x0@0x9943c).
   */
struct wpp_BatteryVoltageMv {
    short voltage_mv;
};

/* WPP object type 293 (DebugDumpIgnoreData), 4 bytes; encoder 0x99440
   (+0x0@0x99460).
   */
struct wpp_DebugDumpIgnoreData {
    unsigned int reason;
};

/* WPP object type 294 (AlarmId), 1 bytes; parser 0x4ef54 (+0x0@0x4ef5c). */
struct wpp_AlarmId {
    unsigned char id;
};

/* WPP object type 295 (NbAlarm), 1 bytes; encoder 0x99464 (+0x0@0x99484). */
struct wpp_NbAlarm {
    unsigned char nb;
};

/* WPP object type 296 (PlsReturnCode), 16 bytes; encoder 0x99488
   (+0x0@0x994a4 +0x4@0x994ac +0x8@0x994b4 +0xc@0x994c0).
   */
struct wpp_PlsReturnCode {
    unsigned int err;
    unsigned int total;
    unsigned int free;
    unsigned int used;
};

/* WPP object type 297 (PlsStation), 8 bytes; encoder 0x994c4
   (+0x0@0x994e0 +0x4@0x994ec); parser 0x4ef80 (+0x0@0x4ef8c
   +0x4@0x4ef94).
   */
struct wpp_PlsStation {
    unsigned short id;
    unsigned char pad_2[0x2];
    unsigned int timestamp;
};

/* WPP object type 298 (AppProbe), 8 bytes; parser 0x4efb8 (+0x0@0x4efc4
   +0x1@0x4efcc +0x4@0x4efd4).
   */
struct wpp_AppProbe {
    unsigned char os;
    unsigned char app;
    unsigned char pad_2[0x2];
    unsigned int version;
};

/* WPP object type 300 (FactoryState), 1 bytes; encoder 0x994f0
   (+0x0@0x99510).
   */
struct wpp_FactoryState {
    unsigned char value;
};

/* WPP object type 302 (FactoryResetMode), 4 bytes; parser 0x4eff8
   (+0x0@0x4f000).
   */
struct wpp_FactoryResetMode {
    unsigned int mode;
};

/* WPP object type 303 (TrackerWearPos), 1 bytes; encoder 0x99514
   (+0x0@0x99534); parser 0x4f024 (+0x0@0x4f02c).
   */
struct wpp_TrackerWearPos {
    unsigned char value;
};

/* WPP object type 307 (FeatureMask), 4 bytes; encoder 0x99538
   (+0x0@0x99558); parser 0x4f050 (+0x0@0x4f058).
   */
struct wpp_FeatureMask {
    unsigned int mask;
};

/* WPP object type 309 (AccountKey), 69 bytes; parser 0x4f07c
   (+0x0@0x4f088 +0x4@0x4f090).
   */
struct wpp_AccountKey {
    unsigned int id;
    unsigned char secret[0x41];
};

/* WPP object type 310 (AdvKey), 65 bytes; parser 0x4f0b8 (+0x0@0x4f0c0). */
struct wpp_AdvKey {
    unsigned char secret[0x41];
};

/* WPP object type 311 (McuId), 8 bytes; encoder 0x9955c (+0x0@0x99578
   +0x4@0x99584).
   */
struct wpp_McuId {
    unsigned int high;
    unsigned int low;
};

/* WPP object type 312 (SensorId), 65 bytes; parser 0x4f0e8
   (+0x0@0x4f0f0).
   */
struct wpp_SensorId {
    unsigned char id[0x41];
};

/* WPP object type 313 (SoftdeviceVersion), 12 bytes; encoder 0x99588
   (+0x0@0x995a4 +0x4@0x995ac +0x8@0x995b8).
   */
struct wpp_SoftdeviceVersion {
    unsigned int version;
    unsigned int subversion;
    unsigned int company_id;
};

/* WPP object type 314 (HrAutoAlgo), 1 bytes; encoder 0x995bc
   (+0x0@0x995dc); parser 0x4f118 (+0x0@0x4f120).
   */
struct wpp_HrAutoAlgo {
    unsigned char mode;
};

/* WPP object type 316 (WorkoutScreenList), 32 bytes; encoder 0x995e0
   (+0x0@0x99602).
   */
struct wpp_WorkoutScreenList {
    unsigned int screen_nb[0x8];
};

/* WPP object type 320 (SyncRequest), 4 bytes; encoder 0x99606
   (+0x0@0x99622 +0x2@0x9962e).
   */
struct wpp_SyncRequest {
    unsigned short type;
    unsigned short reserved;
};

/* WPP object type 322 (Silent), 1 bytes; parser 0x4f1c8 (+0x0@0x4f1d0). */
struct wpp_Silent {
    unsigned char value;
};

/* WPP object type 323 (StoredSignalMeta), 8 bytes; encoder 0x99632
   (+0x0@0x9964e +0x2@0x99656 +0x4@0x9965e +0x5@0x99666 +0x6@0x9966e
   +0x7@0x9967a).
   */
struct wpp_StoredSignalMeta {
    unsigned short type;
    unsigned short sampling_freq;
    unsigned char format;
    unsigned char size;
    unsigned char resolution;
    unsigned char channel;
};

/* WPP object type 324 (StoredSignalData), 65 bytes; encoder 0x9967e
   (+0x0@0x996a0).
   */
struct wpp_StoredSignalData {
    unsigned char samples[0x41];
};

/* WPP object type 325 (Id), 4 bytes; encoder 0x996a4 (+0x0@0x996c4). */
struct wpp_Id {
    unsigned int value;
};

/* WPP object type 326 (StoredSignalMetaExtend), 12 bytes; encoder 0x996c8
   (+0x0@0x996e4 +0x4@0x996ec +0x8@0x996f8).
   */
struct wpp_StoredSignalMetaExtend {
    unsigned int duration;
    unsigned int total_size;
    unsigned int filter_bank;
};

/* WPP object type 327 (UnitConversionParameters), 12 bytes; encoder
   0x996fc (+0x0@0x99718 +0x4@0x99720 +0x8@0x9972c).
   */
struct wpp_UnitConversionParameters {
    unsigned int offset;
    unsigned int gain;
    unsigned int qfix;
};

/* WPP object type 329 (AlgorithmVersion), 8 bytes; encoder 0x99730
   (+0x0@0x9974c +0x4@0x99758).
   */
struct wpp_AlgorithmVersion {
    unsigned int type;
    unsigned int version;
};

/* WPP object type 330 (FirmwareVersion), 4 bytes; encoder 0x9975c
   (+0x0@0x9977c).
   */
struct wpp_FirmwareVersion {
    unsigned int version;
};

/* WPP object type 516 (Gpio), 6 bytes; encoder 0x99780 (+0x0@0x9979e
   +0x1@0x997a8 +0x2@0x997b2 +0x3@0x997bc +0x4@0x997c6 +0x5@0x997d4);
   parser 0x4f308 (+0x0@0x4f314 +0x1@0x4f31c +0x2@0x4f324 +0x3@0x4f32c
   +0x4@0x4f334 +0x5@0x4f33c).
   */
struct wpp_Gpio {
    signed char cmd;
    signed char bank;
    signed char gpio;
    signed char mode;
    signed char state;
    signed char rc;
};

/* WPP object type 518 (Uint32), 4 bytes; encoder 0x997d8 (+0x0@0x997f8);
   parser 0x4f360 (+0x0@0x4f368).
   */
struct wpp_Uint32 {
    unsigned int val;
};

/* WPP object type 519 (WppString), 65 bytes; encoder 0x997fc
   (+0x0@0x9981e); parser 0x4f38c (+0x0@0x4f394).
   */
struct wpp_WppString {
    unsigned char val[0x41];
};

/* WPP object type 535 (Int32), 4 bytes; encoder 0x99822 (+0x0@0x99842). */
struct wpp_Int32 {
    unsigned int val;
};

/* WPP object type 1025 (UpdateFirmware), 8 bytes; parser 0x4f3e8
   (+0x0@0x4f3f4 +0x4@0x4f3fc).
   */
struct wpp_UpdateFirmware {
    unsigned char fw_type;
    unsigned char pad_1[0x3];
    unsigned int fw_size;
};

/* WPP object type 1043 (Mac), 65 bytes; encoder 0x99846 (+0x0@0x99868). */
struct wpp_Mac {
    unsigned char mac[0x41];
};

/* WPP object type 1281 (TimeSet), 16 bytes; encoder 0x9986c (+0x0@0x99888
   +0x4@0x99890 +0x8@0x99898 +0xc@0x998a4); parser 0x4f420 (+0x0@0x4f42c
   +0x4@0x4f434 +0x8@0x4f43e +0xc@0x4f448).
   */
struct wpp_TimeSet {
    unsigned int utc;
    unsigned int gmt_offset;
    unsigned int dst_change_time;
    unsigned int next_gmt_offset;
};

/* WPP object type 1282 (TimeSetReply), 4 bytes; encoder 0x998a8
   (+0x0@0x998c8).
   */
struct wpp_TimeSetReply {
    unsigned int drift;
};

/* WPP object type 1283 (TrackerUser), 85 bytes; encoder 0x998cc
   (+0x0@0x998ec +0x4@0x998f4 +0x8@0x998fc +0xc@0x99904 +0x10@0x9990c
   +0x14@0x9991a); parser 0x4f46c (+0x0@0x4f478 +0x4@0x4f480 +0x8@0x4f48a
   +0xc@0x4f494 +0x10@0x4f49e +0x14@0x4f4a8).
   */
struct wpp_TrackerUser {
    unsigned int id;
    unsigned int weight;
    unsigned int height;
    unsigned char gender;
    unsigned char pad_d[0x3];
    unsigned int birth;
    unsigned char first_name[0x41];
};

/* WPP object type 1284 (BatteryStatus), 12 bytes; encoder 0x9991e
   (+0x0@0x9993a +0x1@0x99942 +0x4@0x9994a +0x8@0x99956).
   */
struct wpp_BatteryStatus {
    unsigned char battery_percent;
    unsigned char battery_state;
    unsigned char pad_2[0x2];
    unsigned int battery_mv;
    unsigned int reserved;
};

/* WPP object type 1286 (WamVasistasGet), 6 bytes; parser 0x4f4d0
   (+0x0@0x4f4dc +0x4@0x4f4e4).
   */
struct wpp_WamVasistasGet {
    unsigned int utc_start;
    unsigned short max;
};

/* WPP object type 1287 (WamDailyActivities), 20 bytes; encoder 0x9995a
   (+0x0@0x99976 +0x4@0x9997e +0x8@0x99986 +0xc@0x9998e +0x10@0x9999a).
   */
struct wpp_WamDailyActivities {
    unsigned int steps;
    unsigned int distance;
    unsigned int ascent;
    unsigned int descent;
    unsigned int calories;
};

/* WPP object type 1289 (WamScreensList), 24 bytes; encoder 0x9999e
   (+0x0@0x999c0); parser 0x4f508 (+0x0@0x4f510).
   */
struct wpp_WamScreensList {
    unsigned char screen_numbers[0x18];
};

/* WPP object type 1292 (HandsMove), 4 bytes; parser 0x4f534 (+0x0@0x4f540
   +0x2@0x4f548).
   */
struct wpp_HandsMove {
    unsigned char hand;
    unsigned char pad_1[0x1];
    unsigned short nb_steps;
};

/* WPP object type 1297 (TrackerGoal), 8 bytes; parser 0x4f56c
   (+0x0@0x4f578 +0x4@0x4f580).
   */
struct wpp_TrackerGoal {
    unsigned int goal_type;
    unsigned int value;
};

/* WPP object type 1298 (Alarm), 7 bytes; encoder 0x999c4 (+0x0@0x999e0
   +0x1@0x999e8 +0x2@0x999f0 +0x3@0x999f8 +0x4@0x99a00 +0x5@0x99a08
   +0x6@0x99a14); parser 0x4f5a4 (+0x0@0x4f5b0 +0x1@0x4f5b8 +0x2@0x4f5c0
   +0x3@0x4f5c8 +0x4@0x4f5d0 +0x5@0x4f5d8 +0x6@0x4f5e0).
   */
struct wpp_Alarm {
    unsigned char hour;
    unsigned char minute;
    unsigned char wday;
    unsigned char mday;
    unsigned char month;
    unsigned char year;
    unsigned char span;
};

/* WPP object type 1299 (UserSecret), 65 bytes; parser 0x4f604
   (+0x0@0x4f60c).
   */
struct wpp_UserSecret {
    unsigned char user_secret[0x41];
};

/* WPP object type 1300 (Name), 65 bytes; encoder 0x99a18 (+0x0@0x99a3a). */
struct wpp_Name {
    unsigned char str[0x41];
};

/* WPP object type 1301 (VasistasType), 4 bytes; parser 0x4f664
   (+0x0@0x4f66c).
   */
struct wpp_VasistasType {
    unsigned int value;
};

/* WPP object type 1537 (WamVasistasHead), 4 bytes; encoder 0x99a3e
   (+0x0@0x99a5e).
   */
struct wpp_WamVasistasHead {
    unsigned int utc;
};

/* WPP object type 1538 (WamVasistasDuration), 2 bytes; encoder 0x99a62
   (+0x0@0x99a82).
   */
struct wpp_WamVasistasDuration {
    unsigned short duration;
};

/* WPP object type 1539 (WamVasistasAwake), 16 bytes; encoder 0x99a86
   (+0x0@0x99aa2 +0x4@0x99aaa +0x8@0x99ab2 +0xc@0x99abe).
   */
struct wpp_WamVasistasAwake {
    unsigned short steps;
    unsigned char pad_2[0x2];
    unsigned int distance;
    unsigned int ascent;
    unsigned int descent;
};

/* WPP object type 1540 (WamVasistasWalk), 2 bytes; encoder 0x99ac2
   (+0x0@0x99ae2).
   */
struct wpp_WamVasistasWalk {
    unsigned short level;
};

/* WPP object type 1541 (WamVasistasRun), 2 bytes; encoder 0x99ae6
   (+0x0@0x99b06).
   */
struct wpp_WamVasistasRun {
    unsigned short level;
};

/* WPP object type 1543 (WamVasistasSleep), 2 bytes; encoder 0x99b0a
   (+0x0@0x99b2a).
   */
struct wpp_WamVasistasSleep {
    unsigned short level;
};

/* WPP object type 1544 (WamVasistasMetCal), 4 bytes; encoder 0x99b2e
   (+0x0@0x99b4a +0x2@0x99b56).
   */
struct wpp_WamVasistasMetCal {
    unsigned short calories;
    unsigned short met;
};

/* WPP object type 1545 (VasistasSwimV1), 5 bytes; encoder 0x99b5a
   (+0x0@0x99b76 +0x4@0x99b82).
   */
struct wpp_VasistasSwimV1 {
    unsigned int mvt;
    unsigned char laps;
};

/* WPP object type 1546 (WamVasistasMetCalEarned), 4 bytes; encoder
   0x99b86 (+0x0@0x99ba2 +0x2@0x99bae).
   */
struct wpp_WamVasistasMetCalEarned {
    unsigned short calories;
    unsigned short met;
};

/* WPP object type 1547 (VasistasActiRecoV1V2), 4 bytes; encoder 0x99bb2
   (+0x0@0x99bce +0x2@0x99bda).
   */
struct wpp_VasistasActiRecoV1V2 {
    unsigned short reco_v1;
    unsigned short reco_v2;
};

/* WPP object type 1549 (VasistasSwimType), 1 bytes; encoder 0x99bde
   (+0x0@0x99bfe).
   */
struct wpp_VasistasSwimType {
    unsigned char value;
};

/* WPP object type 2328 (ReturnCode), 4 bytes; encoder 0x99c02
   (+0x0@0x99c22).
   */
struct wpp_ReturnCode {
    unsigned int rc;
};

/* WPP object type 2329 (AlarmEnabled), 1 bytes; encoder 0x99c26
   (+0x0@0x99c46); parser 0x4f6f0 (+0x0@0x4f6f8).
   */
struct wpp_AlarmEnabled {
    unsigned char state;
};

/* WPP object type 2332 (CalibrationSession), 8 bytes; parser 0x4f71c
   (+0x0@0x4f728 +0x4@0x4f730).
   */
struct wpp_CalibrationSession {
    unsigned int param0;
    unsigned int param1;
};

/* WPP object type 2344 (AppProbeOsVersion), 2 bytes; parser 0x4f754
   (+0x0@0x4f75c).
   */
struct wpp_AppProbeOsVersion {
    unsigned short os_version;
};

/* WPP object type 2345 (VasistasHeartrate), 4 bytes; encoder 0x99c4a
   (+0x0@0x99c66 +0x1@0x99c6e +0x2@0x99c7a).
   */
struct wpp_VasistasHeartrate {
    unsigned char heartrate;
    unsigned char quality;
    unsigned short temperature;
};

/* WPP object type 2346 (AncsStatus), 1 bytes; encoder 0x99c7e
   (+0x0@0x99c9e).
   */
struct wpp_AncsStatus {
    unsigned char status;
};

/* WPP object type 2350 (TempCalReply), 12 bytes; encoder 0x99ca2
   (+0x0@0x99cbe +0x4@0x99cc6 +0x8@0x99cd2).
   */
struct wpp_TempCalReply {
    unsigned char point_idx;
    unsigned char pad_1[0x3];
    unsigned int temp_mili;
    unsigned int raw_value;
};

/* WPP object type 2352 (CalibrationPoint), 12 bytes; encoder 0x99cd6
   (+0x0@0x99cf2 +0x4@0x99cfa +0x8@0x99d06).
   */
struct wpp_CalibrationPoint {
    unsigned char point_idx;
    unsigned char pad_1[0x3];
    unsigned int reference;
    unsigned int value;
};

/* WPP object type 2356 (LightSensorReply), 8 bytes; encoder 0x99d0a
   (+0x0@0x99d26 +0x4@0x99d32).
   */
struct wpp_LightSensorReply {
    unsigned int value;
    unsigned int type;
};

/* WPP object type 2357 (CustomizationIdGet), 4 bytes; encoder 0x99d36
   (+0x0@0x99d56); parser 0x4f850 (+0x0@0x4f858).
   */
struct wpp_CustomizationIdGet {
    unsigned int identifier;
};

/* WPP object type 2358 (CustomizationIdSet), 4 bytes; encoder 0x99d5a
   (+0x0@0x99d7a); parser 0x4f87c (+0x0@0x4f884).
   */
struct wpp_CustomizationIdSet {
    unsigned int identifier;
};

/* WPP object type 2359 (LuminosityLevel), 2 bytes; encoder 0x99d7e
   (+0x0@0x99d9a +0x1@0x99da6).
   */
struct wpp_LuminosityLevel {
    unsigned char mode;
    unsigned char level;
};

/* WPP object type 2369 (LiveHr), 1 bytes; encoder 0x99daa (+0x0@0x99dca). */
struct wpp_LiveHr {
    unsigned char hr;
};

/* WPP object type 2370 (UnknownSteps), 4 bytes; encoder 0x99dce
   (+0x0@0x99dee).
   */
struct wpp_UnknownSteps {
    unsigned int steps;
};

/* WPP object type 2372 (SpiFlashCmd), 16 bytes; parser 0x4f8e0
   (+0x0@0x4f8ec +0x4@0x4f8f4 +0x8@0x4f8fe +0xc@0x4f908).
   */
struct wpp_SpiFlashCmd {
    unsigned int cmd;
    unsigned int arg1;
    unsigned int arg2;
    unsigned int arg3;
};

/* WPP object type 2373 (SpiFlashChunk), 16 bytes; encoder 0x99df2
   (+0x0@0x99e14).
   */
struct wpp_SpiFlashChunk {
    unsigned char chunk[0x10];
};

/* WPP object type 2388 (BatteryStateOpt), 4 bytes; parser 0x4f96c
   (+0x0@0x4f974).
   */
struct wpp_BatteryStateOpt {
    unsigned int value;
};

/* WPP object type 2389 (ScreenState), 1 bytes; parser 0x4f998
   (+0x0@0x4f9a0).
   */
struct wpp_ScreenState {
    unsigned char value;
};

/* WPP object type 2390 (Steps), 4 bytes; encoder 0x99e18 (+0x0@0x99e38);
   parser 0x4f9c4 (+0x0@0x4f9cc).
   */
struct wpp_Steps {
    unsigned int value;
};

/* WPP object type 2391 (Calories), 4 bytes; encoder 0x99e3c
   (+0x0@0x99e5c); parser 0x4f9f0 (+0x0@0x4f9f8).
   */
struct wpp_Calories {
    unsigned int value;
};

/* WPP object type 2392 (Distance), 4 bytes; encoder 0x99e60
   (+0x0@0x99e80); parser 0x4fa1c (+0x0@0x4fa24).
   */
struct wpp_Distance {
    unsigned int value;
};

/* WPP object type 2394 (InfoType), 1 bytes; parser 0x4fa48
   (+0x0@0x4fa50).
   */
struct wpp_InfoType {
    unsigned char value;
};

/* WPP object type 2395 (Duration), 4 bytes; encoder 0x99e84
   (+0x0@0x99ea4); parser 0x4fa74 (+0x0@0x4fa7c).
   */
struct wpp_Duration {
    unsigned int value;
};

/* WPP object type 2396 (GlyphId), 4 bytes; encoder 0x99ea8
   (+0x0@0x99ec8).
   */
struct wpp_GlyphId {
    unsigned int unicode;
};

/* WPP object type 2397 (ImageMetadata), 3 bytes; encoder 0x99ecc
   (+0x0@0x99ee8 +0x1@0x99ef0 +0x2@0x99efc).
   */
struct wpp_ImageMetadata {
    unsigned char type;
    unsigned char width;
    unsigned char height;
};

/* WPP object type 2401 (Version), 1 bytes; encoder 0x99f00
   (+0x0@0x99f20); parser 0x4fb3c (+0x0@0x4fb44).
   */
struct wpp_Version {
    unsigned char value;
};

/* WPP object type 2403 (NotificationAppInfo), 66 bytes; encoder 0x99f24
   (+0x0@0x99f42 +0x41@0x99f50).
   */
struct wpp_NotificationAppInfo {
    unsigned char name[0x41];
    unsigned char category;
};

/* WPP object type 2404 (NotificationAppId), 65 bytes; encoder 0x99f54
   (+0x0@0x99f76).
   */
struct wpp_NotificationAppId {
    unsigned char id[0x41];
};

/* WPP object type 2406 (NotificationAppHashIdVersion), 1 bytes; encoder
   0x99f7a (+0x0@0x99f9a).
   */
struct wpp_NotificationAppHashIdVersion {
    unsigned char version;
};

/* WPP object type 2407 (NotificationAppHashIdCrc32), 4 bytes; encoder
   0x99f9e (+0x0@0x99fbe).
   */
struct wpp_NotificationAppHashIdCrc32 {
    unsigned int hash_id;
};

/* WPP object type 2408 (CacheType), 1 bytes; parser 0x4fc08
   (+0x0@0x4fc10).
   */
struct wpp_CacheType {
    unsigned char type;
};

/* WPP object type 2409 (ActivitySubcategory), 2 bytes; encoder 0x99fc2
   (+0x0@0x99fe4).
   */
struct wpp_ActivitySubcategory {
    short value;
};

/* WPP object type 2410 (Timestamp), 4 bytes; encoder 0x99fe8
   (+0x0@0x9a008).
   */
struct wpp_Timestamp {
    unsigned int value;
};

/* WPP object type 2414 (FwInfo), 32 bytes; parser 0x4fce4 (+0x0@0x4fcf0
   +0x4@0x4fcf8 +0x8@0x4fd02 +0xc@0x4fd0e).
   */
struct wpp_FwInfo {
    unsigned int version;
    unsigned int size;
    unsigned int crc;
    unsigned char sha1[0x14];
};

/* WPP object type 2415 (FwChunkRequest), 14 bytes; encoder 0x9a00c
   (+0x0@0x9a028 +0x4@0x9a030 +0x8@0x9a038 +0xc@0x9a040 +0xd@0x9a04c).
   */
struct wpp_FwChunkRequest {
    unsigned int version;
    unsigned int offset;
    unsigned int size;
    unsigned char percent;
    unsigned char packet_max_size;
};

/* WPP object type 2418 (StartTime), 4 bytes; encoder 0x9a050
   (+0x0@0x9a070).
   */
struct wpp_StartTime {
    unsigned int value;
};

/* WPP object type 2419 (EndTime), 4 bytes; encoder 0x9a074
   (+0x0@0x9a094).
   */
struct wpp_EndTime {
    unsigned int value;
};

/* WPP object type 2420 (Status), 1 bytes; encoder 0x9a098 (+0x0@0x9a0ba). */
struct wpp_Status {
    signed char value;
};

/* WPP object type 2421 (TestScreen), 1 bytes; parser 0x4fdd0
   (+0x0@0x4fdd8).
   */
struct wpp_TestScreen {
    unsigned char value;
};

/* WPP object type 2422 (ChallengeRequest), 1 bytes; parser 0x4fdfc
   (+0x0@0x4fe04).
   */
struct wpp_ChallengeRequest {
    unsigned char value;
};

/* WPP object type 2424 (DebugDumpAnchor), 4 bytes; encoder 0x9a0be
   (+0x0@0x9a0de).
   */
struct wpp_DebugDumpAnchor {
    unsigned int value;
};

/* WPP object type 2425 (FactoryMode), 4 bytes; encoder 0x9a0e2
   (+0x0@0x9a102); parser 0x4fe54 (+0x0@0x4fe5c).
   */
struct wpp_FactoryMode {
    unsigned int mode;
};

/* WPP object type 2426 (GlanceStatus), 1 bytes; encoder 0x9a106
   (+0x0@0x9a126); parser 0x4fe80 (+0x0@0x4fe88).
   */
struct wpp_GlanceStatus {
    unsigned char status;
};

/* WPP object type 2427 (MeasureCategory), 2 bytes; encoder 0x9a12a
   (+0x0@0x9a14c).
   */
struct wpp_MeasureCategory {
    short value;
};

/* WPP object type 2428 (MeasureLiveMeta), 4 bytes; encoder 0x9a150
   (+0x0@0x9a170).
   */
struct wpp_MeasureLiveMeta {
    unsigned int time_window;
};

/* WPP object type 2429 (MeasureLiveEcg), 65 bytes; encoder 0x9a174
   (+0x0@0x9a196).
   */
struct wpp_MeasureLiveEcg {
    unsigned char samples[0x41];
};

/* WPP object type 2430 (MeasureStopReason), 4 bytes; encoder 0x9a19a
   (+0x0@0x9a1ba).
   */
struct wpp_MeasureStopReason {
    unsigned int value;
};

/* WPP object type 2431 (PressureTemperature), 40 bytes; encoder 0x9a1be
   (+0x0@0x9a1da +0x4@0x9a1e2 +0x8@0x9a1f0).
   */
struct wpp_PressureTemperature {
    unsigned int pressure;
    unsigned int temperature;
    unsigned int calib_coefs[0x8];
};

/* WPP object type 2432 (AltimeterCompensation), 4 bytes; parser 0x4fed8
   (+0x0@0x4fee0).
   */
struct wpp_AltimeterCompensation {
    unsigned int val;
};

/* WPP object type 2436 (ActivityLap), 1 bytes; encoder 0x9a1f4
   (+0x0@0x9a216).
   */
struct wpp_ActivityLap {
    signed char value;
};

/* WPP object type 2438 (ActivityPause), 1 bytes; encoder 0x9a21a
   (+0x0@0x9a23c).
   */
struct wpp_ActivityPause {
    signed char value;
};

/* WPP object type 2439 (PauseState), 12 bytes; encoder 0x9a240
   (+0x0@0x9a25e +0x4@0x9a266 +0x8@0x9a272).
   */
struct wpp_PauseState {
    signed char value;
    unsigned char pad_1[0x3];
    unsigned int start_time;
    unsigned int sum;
};

/* WPP object type 2443 (RebootOptional), 1 bytes; encoder 0x9a276
   (+0x0@0x9a296); parser 0x4ff44 (+0x0@0x4ff4c).
   */
struct wpp_RebootOptional {
    unsigned char value;
};

/* WPP object type 2445 (DigitalCrownMotionDelta), 4 bytes; encoder
   0x9a29a (+0x0@0x9a2b8 +0x2@0x9a2c6).
   */
struct wpp_DigitalCrownMotionDelta {
    short x;
    short y;
};

/* WPP object type 2448 (MtuWpp), 2 bytes; encoder 0x9a2ca (+0x0@0x9a2ea);
   parser 0x4ff70 (+0x0@0x4ff78).
   */
struct wpp_MtuWpp {
    unsigned short max_recv_size;
};

/* WPP object type 2449 (MtuTls), 2 bytes; encoder 0x9a2ee (+0x0@0x9a30e). */
struct wpp_MtuTls {
    unsigned short mtu;
};

/* WPP object type 2450 (MtuAttBle), 2 bytes; encoder 0x9a312
   (+0x0@0x9a332).
   */
struct wpp_MtuAttBle {
    unsigned short mtu;
};

/* WPP object type 2452 (Heartrate), 1 bytes; encoder 0x9a336
   (+0x0@0x9a356).
   */
struct wpp_Heartrate {
    unsigned char heartrate;
};

/* WPP object type 2453 (VasistasSpo2), 6 bytes; encoder 0x9a35a
   (+0x0@0x9a376 +0x2@0x9a37e +0x4@0x9a38a).
   */
struct wpp_VasistasSpo2 {
    unsigned short spo2;
    unsigned short quality;
    unsigned short error;
};

/* WPP object type 2461 (VasistasFlags), 4 bytes; encoder 0x9a38e
   (+0x0@0x9a3aa +0x2@0x9a3b6).
   */
struct wpp_VasistasFlags {
    unsigned short enabled_flags;
    unsigned short supported_flags;
};

/* WPP object type 2464 (VasistasAhi), 4 bytes; encoder 0x9a3ba
   (+0x0@0x9a3d8 +0x2@0x9a3e6).
   */
struct wpp_VasistasAhi {
    short ahi;
    short bd_proba;
};

/* WPP object type 2465 (ShortcutAction), 1 bytes; encoder 0x9a3ea
   (+0x0@0x9a40a).
   */
struct wpp_ShortcutAction {
    unsigned char value;
};

/* WPP object type 2471 (NotificationsDisplayState), 1 bytes; encoder
   0x9a40e (+0x0@0x9a42e).
   */
struct wpp_NotificationsDisplayState {
    unsigned char status;
};

/* WPP object type 2472 (LocalNotification), 5 bytes; encoder 0x9a432
   (+0x0@0x9a44e +0x4@0x9a45a).
   */
struct wpp_LocalNotification {
    unsigned int id;
    unsigned char status;
};

/* WPP object type 2473 (EventV2), 12 bytes; encoder 0x9a45e (+0x0@0x9a47a
   +0x4@0x9a482 +0x8@0x9a48e).
   */
struct wpp_EventV2 {
    unsigned int type;
    unsigned int epoch;
    unsigned int userid;
};

/* WPP object type 2474 (Boolean), 1 bytes; encoder 0x9a492
   (+0x0@0x9a4b2); parser 0x50164 (+0x0@0x5016c).
   */
struct wpp_Boolean {
    unsigned char value;
};

/* WPP object type 2477 (InactivityCfg), 5 bytes; encoder 0x9a4b6
   (+0x0@0x9a4d2 +0x1@0x9a4da +0x2@0x9a4e2 +0x3@0x9a4ea +0x4@0x9a4f6).
   */
struct wpp_InactivityCfg {
    unsigned char from_hour;
    unsigned char from_minute;
    unsigned char to_hour;
    unsigned char to_minute;
    unsigned char wday;
};

/* WPP object type 2489 (AlgoParam), 8 bytes; encoder 0x9a4fa
   (+0x0@0x9a518 +0x4@0x9a524).
   */
struct wpp_AlgoParam {
    short id;
    unsigned char pad_2[0x2];
    unsigned int value;
};

/* WPP object type 2490 (Stairs), 4 bytes; encoder 0x9a528 (+0x0@0x9a548);
   parser 0x501e0 (+0x0@0x501e8).
   */
struct wpp_Stairs {
    unsigned int value;
};

/* WPP object type 2491 (MoveHands), 1 bytes; encoder 0x9a54c
   (+0x0@0x9a56c); parser 0x5020c (+0x0@0x50214).
   */
struct wpp_MoveHands {
    unsigned char value;
};

/* WPP object type 2493 (WorkoutMaxNumber), 1 bytes; encoder 0x9a570
   (+0x0@0x9a590).
   */
struct wpp_WorkoutMaxNumber {
    unsigned char value;
};

/* WPP object type 2496 (SkinTemperatureMeasureResult), 6 bytes; encoder
   0x9a594 (+0x0@0x9a5b2 +0x2@0x9a5bc +0x4@0x9a5ca).
   */
struct wpp_SkinTemperatureMeasureResult {
    short temp_q7;
    short integer;
    short fraction;
};

/* WPP object type 2497 (FluxSensorMeasureResult), 8 bytes; encoder
   0x9a5ce (+0x0@0x9a5ea +0x4@0x9a5f6).
   */
struct wpp_FluxSensorMeasureResult {
    unsigned int value_uv;
    unsigned int value_adc;
};

/* WPP object type 2498 (DeviceChallengeRequest), 65 bytes; parser 0x50238
   (+0x0@0x50240).
   */
struct wpp_DeviceChallengeRequest {
    unsigned char platform_random[0x41];
};

/* WPP object type 2499 (DeviceChallengeReply), 136 bytes; encoder 0x9a5fa
   (+0x0@0x9a61e +0x41@0x9a628 +0x84@0x9a636).
   */
struct wpp_DeviceChallengeReply {
    unsigned char platform_random[0x41];
    unsigned char device_random[0x41];
    unsigned char pad_82[0x2];
    unsigned int signature_algo_id;
};

/* WPP object type 2500 (DeviceChallengeSignature), 65 bytes; encoder
   0x9a63a (+0x0@0x9a65c).
   */
struct wpp_DeviceChallengeSignature {
    unsigned char data[0x41];
};

/* WPP object type 2501 (FactoryTestDsc), 8 bytes; encoder 0x9a660
   (+0x0@0x9a67c +0x1@0x9a684 +0x4@0x9a690); parser 0x50268 (+0x0@0x50274
   +0x1@0x5027c +0x4@0x50284).
   */
struct wpp_FactoryTestDsc {
    unsigned char type;
    unsigned char status;
    unsigned char pad_2[0x2];
    unsigned int arg;
};

/* WPP object type 2502 (VasistasCbt), 8 bytes; encoder 0x9a694
   (+0x0@0x9a6b0 +0x1@0x9a6b8 +0x4@0x9a6c4).
   */
struct wpp_VasistasCbt {
    unsigned char algo;
    unsigned char attrib;
    unsigned char pad_2[0x2];
    unsigned int temperature;
};

/* WPP object type 2505 (Max86173ChannelStats), 85 bytes; encoder 0x9a6c8
   (+0x0@0x9a6ec +0x2@0x9a6f4 +0x44@0x9a6fc +0x48@0x9a704 +0x4c@0x9a70c
   +0x50@0x9a716 +0x52@0x9a720 +0x53@0x9a72a +0x54@0x9a738).
   */
struct wpp_Max86173ChannelStats {
    unsigned short tag;
    unsigned char channel_name[0x41];
    unsigned char pad_43[0x1];
    unsigned int avg_paperma;
    unsigned int avg_adc;
    unsigned int std_adc;
    unsigned short led_value;
    unsigned char adc_range;
    unsigned char led_range;
    unsigned char agc_changes;
};

/* WPP object type 2506 (GreentegSensitivityBin), 65 bytes; encoder
   0x9a73c (+0x0@0x9a75e); parser 0x502a8 (+0x0@0x502b0).
   */
struct wpp_GreentegSensitivityBin {
    unsigned char reel_char[0x41];
};

/* WPP object type 2507 (DigitalCrownScaleFactor), 4 bytes; encoder
   0x9a762 (+0x0@0x9a77e +0x2@0x9a78a); parser 0x502d8 (+0x0@0x502e4
   +0x2@0x502ec).
   */
struct wpp_DigitalCrownScaleFactor {
    unsigned short numerator;
    unsigned short denominator;
};

/* WPP object type 2508 (SymptomType), 2 bytes; parser 0x50310
   (+0x0@0x50318).
   */
struct wpp_SymptomType {
    unsigned short id;
};

/* WPP object type 2509 (SymptomListItem), 77 bytes; encoder 0x9a78e
   (+0x0@0x9a7ae +0x4@0x9a7b6 +0x8@0x9a7be +0xc@0x9a7cc).
   */
struct wpp_SymptomListItem {
    unsigned int id;
    unsigned char activated;
    unsigned char pad_5[0x3];
    unsigned int timestamp;
    unsigned char label[0x41];
};

/* WPP object type 2511 (VibratorSetSimple), 5 bytes; parser 0x503f4
   (+0x0@0x50400 +0x2@0x50408 +0x4@0x50410).
   */
struct wpp_VibratorSetSimple {
    unsigned short duration_on_ms;
    unsigned short duration_off_ms;
    unsigned char nb_loop;
};

/* WPP object type 2512 (CycleTrackingMenstruationStart), 4 bytes; encoder
   0x9a7d0 (+0x0@0x9a7f0).
   */
struct wpp_CycleTrackingMenstruationStart {
    unsigned int timestamp;
};

/* WPP object type 2518 (GreentegIntegrationFactor), 4 bytes; encoder
   0x9a7f4 (+0x0@0x9a814); parser 0x50434 (+0x0@0x5043c).
   */
struct wpp_GreentegIntegrationFactor {
    unsigned int value;
};

/* WPP object type 2520 (VasistasHrv), 7 bytes; encoder 0x9a818
   (+0x0@0x9a834 +0x2@0x9a83c +0x4@0x9a844 +0x6@0x9a850).
   */
struct wpp_VasistasHrv {
    unsigned char hr;
    unsigned char pad_1[0x1];
    unsigned short sdnn;
    unsigned short rmssd;
    unsigned char quality;
};

/* WPP object type 2521 (VasistasRr), 2 bytes; encoder 0x9a854
   (+0x0@0x9a874).
   */
struct wpp_VasistasRr {
    unsigned short rr;
};

/* WPP object type 2523 (VasistasDbt), 9 bytes; encoder 0x9a878
   (+0x0@0x9a894 +0x1@0x9a89c +0x2@0x9a8a4 +0x3@0x9a8ac +0x4@0x9a8b4
   +0x5@0x9a8bc +0x6@0x9a8c4 +0x7@0x9a8cc +0x8@0x9a8d8).
   */
struct wpp_VasistasDbt {
    unsigned char hr_max_avg;
    unsigned char hr_min_avg;
    unsigned char in_period_ds;
    unsigned char ex_period_ds;
    unsigned char in_period_target_s;
    unsigned char ex_period_target_s;
    unsigned char duration_target;
    unsigned char is_from_ecg;
    unsigned char hr_quality;
};

/* codecs */
extern void wpp_obj_Null_encode(const struct wpp_Null *obj, void **cursor);
extern void wpp_obj_Null_encode_copy_0x9a918(const struct wpp_Null *obj, void **cursor);
extern int wpp_obj_Null_parse(void **cursor, unsigned short len, struct wpp_Null *out);
extern void wpp_obj_BatteryPercent_encode(const struct wpp_BatteryPercent *obj, void **cursor);
extern void wpp_obj_Cmderror_encode(const struct wpp_Cmderror *obj, void **cursor);
extern int wpp_obj_Cmderror_parse(void **cursor, unsigned short len, struct wpp_Cmderror *out);
extern void wpp_obj_StoredMeasureMeta_encode(const struct wpp_StoredMeasureMeta *obj, void **cursor);
extern void wpp_obj_StoredMeasureData_encode(const struct wpp_StoredMeasureData *obj, void **cursor);
extern void wpp_obj_ConnectReason_encode(const struct wpp_ConnectReason *obj, void **cursor);
extern void wpp_obj_UserUnit_encode(const struct wpp_UserUnit *obj, void **cursor);
extern void wpp_obj_DebugDumpData_encode(const struct wpp_DebugDumpData *obj, void **cursor);
extern int wpp_obj_DebugDumpMask_parse(void **cursor, unsigned short len, struct wpp_DebugDumpMask *out);
extern void wpp_obj_DebugDumpType_encode(const struct wpp_DebugDumpType *obj, void **cursor);
extern void wpp_obj_LocaleSet_encode(const struct wpp_LocaleSet *obj, void **cursor);
extern void wpp_obj_ProbeChallenge_encode(const struct wpp_ProbeChallenge *obj, void **cursor);
extern int wpp_obj_ProbeChallenge_parse(void **cursor, unsigned short len, struct wpp_ProbeChallenge *out);
extern void wpp_obj_ProbeChallengeResponse_encode(const struct wpp_ProbeChallengeResponse *obj, void **cursor);
extern int wpp_obj_ProbeChallengeResponse_parse(void **cursor, unsigned short len, struct wpp_ProbeChallengeResponse *out);
extern void wpp_obj_BatteryVoltageMv_encode(const struct wpp_BatteryVoltageMv *obj, void **cursor);
extern void wpp_obj_DebugDumpIgnoreData_encode(const struct wpp_DebugDumpIgnoreData *obj, void **cursor);
extern int wpp_obj_AlarmId_parse(void **cursor, unsigned short len, struct wpp_AlarmId *out);
extern void wpp_obj_NbAlarm_encode(const struct wpp_NbAlarm *obj, void **cursor);
extern void wpp_obj_PlsReturnCode_encode(const struct wpp_PlsReturnCode *obj, void **cursor);
extern void wpp_obj_PlsStation_encode(const struct wpp_PlsStation *obj, void **cursor);
extern int wpp_obj_PlsStation_parse(void **cursor, unsigned short len, struct wpp_PlsStation *out);
extern int wpp_obj_AppProbe_parse(void **cursor, unsigned short len, struct wpp_AppProbe *out);
extern void wpp_obj_FactoryState_encode(const struct wpp_FactoryState *obj, void **cursor);
extern int wpp_obj_FactoryResetMode_parse(void **cursor, unsigned short len, struct wpp_FactoryResetMode *out);
extern void wpp_obj_TrackerWearPos_encode(const struct wpp_TrackerWearPos *obj, void **cursor);
extern int wpp_obj_TrackerWearPos_parse(void **cursor, unsigned short len, struct wpp_TrackerWearPos *out);
extern void wpp_obj_FeatureMask_encode(const struct wpp_FeatureMask *obj, void **cursor);
extern int wpp_obj_FeatureMask_parse(void **cursor, unsigned short len, struct wpp_FeatureMask *out);
extern int wpp_obj_AccountKey_parse(void **cursor, unsigned short len, struct wpp_AccountKey *out);
extern int wpp_obj_AdvKey_parse(void **cursor, unsigned short len, struct wpp_AdvKey *out);
extern void wpp_obj_McuId_encode(const struct wpp_McuId *obj, void **cursor);
extern int wpp_obj_SensorId_parse(void **cursor, unsigned short len, struct wpp_SensorId *out);
extern void wpp_obj_SoftdeviceVersion_encode(const struct wpp_SoftdeviceVersion *obj, void **cursor);
extern void wpp_obj_HrAutoAlgo_encode(const struct wpp_HrAutoAlgo *obj, void **cursor);
extern int wpp_obj_HrAutoAlgo_parse(void **cursor, unsigned short len, struct wpp_HrAutoAlgo *out);
extern void wpp_obj_WorkoutScreenList_encode(const struct wpp_WorkoutScreenList *obj, void **cursor);
extern void wpp_obj_SyncRequest_encode(const struct wpp_SyncRequest *obj, void **cursor);
extern int wpp_obj_Silent_parse(void **cursor, unsigned short len, struct wpp_Silent *out);
extern void wpp_obj_StoredSignalMeta_encode(const struct wpp_StoredSignalMeta *obj, void **cursor);
extern void wpp_obj_StoredSignalData_encode(const struct wpp_StoredSignalData *obj, void **cursor);
extern void wpp_obj_Id_encode(const struct wpp_Id *obj, void **cursor);
extern void wpp_obj_StoredSignalMetaExtend_encode(const struct wpp_StoredSignalMetaExtend *obj, void **cursor);
extern void wpp_obj_UnitConversionParameters_encode(const struct wpp_UnitConversionParameters *obj, void **cursor);
extern void wpp_obj_AlgorithmVersion_encode(const struct wpp_AlgorithmVersion *obj, void **cursor);
extern void wpp_obj_FirmwareVersion_encode(const struct wpp_FirmwareVersion *obj, void **cursor);
extern void wpp_obj_Gpio_encode(const struct wpp_Gpio *obj, void **cursor);
extern int wpp_obj_Gpio_parse(void **cursor, unsigned short len, struct wpp_Gpio *out);
extern void wpp_obj_Uint32_encode(const struct wpp_Uint32 *obj, void **cursor);
extern int wpp_obj_Uint32_parse(void **cursor, unsigned short len, struct wpp_Uint32 *out);
extern void wpp_obj_WppString_encode(const struct wpp_WppString *obj, void **cursor);
extern int wpp_obj_WppString_parse(void **cursor, unsigned short len, struct wpp_WppString *out);
extern void wpp_obj_Int32_encode(const struct wpp_Int32 *obj, void **cursor);
extern int wpp_obj_UpdateFirmware_parse(void **cursor, unsigned short len, struct wpp_UpdateFirmware *out);
extern void wpp_obj_Mac_encode(const struct wpp_Mac *obj, void **cursor);
extern void wpp_obj_TimeSet_encode(const struct wpp_TimeSet *obj, void **cursor);
extern int wpp_obj_TimeSet_parse(void **cursor, unsigned short len, struct wpp_TimeSet *out);
extern void wpp_obj_TimeSetReply_encode(const struct wpp_TimeSetReply *obj, void **cursor);
extern void wpp_obj_TrackerUser_encode(const struct wpp_TrackerUser *obj, void **cursor);
extern int wpp_obj_TrackerUser_parse(void **cursor, unsigned short len, struct wpp_TrackerUser *out);
extern void wpp_obj_BatteryStatus_encode(const struct wpp_BatteryStatus *obj, void **cursor);
extern int wpp_obj_WamVasistasGet_parse(void **cursor, unsigned short len, struct wpp_WamVasistasGet *out);
extern void wpp_obj_WamDailyActivities_encode(const struct wpp_WamDailyActivities *obj, void **cursor);
extern void wpp_obj_WamScreensList_encode(const struct wpp_WamScreensList *obj, void **cursor);
extern int wpp_obj_WamScreensList_parse(void **cursor, unsigned short len, struct wpp_WamScreensList *out);
extern int wpp_obj_HandsMove_parse(void **cursor, unsigned short len, struct wpp_HandsMove *out);
extern int wpp_obj_TrackerGoal_parse(void **cursor, unsigned short len, struct wpp_TrackerGoal *out);
extern void wpp_obj_Alarm_encode(const struct wpp_Alarm *obj, void **cursor);
extern int wpp_obj_Alarm_parse(void **cursor, unsigned short len, struct wpp_Alarm *out);
extern int wpp_obj_UserSecret_parse(void **cursor, unsigned short len, struct wpp_UserSecret *out);
extern void wpp_obj_Name_encode(const struct wpp_Name *obj, void **cursor);
extern int wpp_obj_VasistasType_parse(void **cursor, unsigned short len, struct wpp_VasistasType *out);
extern void wpp_obj_WamVasistasHead_encode(const struct wpp_WamVasistasHead *obj, void **cursor);
extern void wpp_obj_WamVasistasDuration_encode(const struct wpp_WamVasistasDuration *obj, void **cursor);
extern void wpp_obj_WamVasistasAwake_encode(const struct wpp_WamVasistasAwake *obj, void **cursor);
extern void wpp_obj_WamVasistasWalk_encode(const struct wpp_WamVasistasWalk *obj, void **cursor);
extern void wpp_obj_WamVasistasRun_encode(const struct wpp_WamVasistasRun *obj, void **cursor);
extern void wpp_obj_WamVasistasSleep_encode(const struct wpp_WamVasistasSleep *obj, void **cursor);
extern void wpp_obj_WamVasistasMetCal_encode(const struct wpp_WamVasistasMetCal *obj, void **cursor);
extern void wpp_obj_VasistasSwimV1_encode(const struct wpp_VasistasSwimV1 *obj, void **cursor);
extern void wpp_obj_WamVasistasMetCalEarned_encode(const struct wpp_WamVasistasMetCalEarned *obj, void **cursor);
extern void wpp_obj_VasistasActiRecoV1V2_encode(const struct wpp_VasistasActiRecoV1V2 *obj, void **cursor);
extern void wpp_obj_VasistasSwimType_encode(const struct wpp_VasistasSwimType *obj, void **cursor);
extern void wpp_obj_ReturnCode_encode(const struct wpp_ReturnCode *obj, void **cursor);
extern void wpp_obj_AlarmEnabled_encode(const struct wpp_AlarmEnabled *obj, void **cursor);
extern int wpp_obj_AlarmEnabled_parse(void **cursor, unsigned short len, struct wpp_AlarmEnabled *out);
extern int wpp_obj_CalibrationSession_parse(void **cursor, unsigned short len, struct wpp_CalibrationSession *out);
extern int wpp_obj_AppProbeOsVersion_parse(void **cursor, unsigned short len, struct wpp_AppProbeOsVersion *out);
extern void wpp_obj_VasistasHeartrate_encode(const struct wpp_VasistasHeartrate *obj, void **cursor);
extern void wpp_obj_AncsStatus_encode(const struct wpp_AncsStatus *obj, void **cursor);
extern void wpp_obj_TempCalReply_encode(const struct wpp_TempCalReply *obj, void **cursor);
extern void wpp_obj_CalibrationPoint_encode(const struct wpp_CalibrationPoint *obj, void **cursor);
extern void wpp_obj_LightSensorReply_encode(const struct wpp_LightSensorReply *obj, void **cursor);
extern void wpp_obj_CustomizationIdGet_encode(const struct wpp_CustomizationIdGet *obj, void **cursor);
extern int wpp_obj_CustomizationIdGet_parse(void **cursor, unsigned short len, struct wpp_CustomizationIdGet *out);
extern void wpp_obj_CustomizationIdSet_encode(const struct wpp_CustomizationIdSet *obj, void **cursor);
extern int wpp_obj_CustomizationIdSet_parse(void **cursor, unsigned short len, struct wpp_CustomizationIdSet *out);
extern void wpp_obj_LuminosityLevel_encode(const struct wpp_LuminosityLevel *obj, void **cursor);
extern void wpp_obj_LiveHr_encode(const struct wpp_LiveHr *obj, void **cursor);
extern void wpp_obj_UnknownSteps_encode(const struct wpp_UnknownSteps *obj, void **cursor);
extern int wpp_obj_SpiFlashCmd_parse(void **cursor, unsigned short len, struct wpp_SpiFlashCmd *out);
extern void wpp_obj_SpiFlashChunk_encode(const struct wpp_SpiFlashChunk *obj, void **cursor);
extern int wpp_obj_BatteryStateOpt_parse(void **cursor, unsigned short len, struct wpp_BatteryStateOpt *out);
extern int wpp_obj_ScreenState_parse(void **cursor, unsigned short len, struct wpp_ScreenState *out);
extern void wpp_obj_Steps_encode(const struct wpp_Steps *obj, void **cursor);
extern int wpp_obj_Steps_parse(void **cursor, unsigned short len, struct wpp_Steps *out);
extern void wpp_obj_Calories_encode(const struct wpp_Calories *obj, void **cursor);
extern int wpp_obj_Calories_parse(void **cursor, unsigned short len, struct wpp_Calories *out);
extern void wpp_obj_Distance_encode(const struct wpp_Distance *obj, void **cursor);
extern int wpp_obj_Distance_parse(void **cursor, unsigned short len, struct wpp_Distance *out);
extern int wpp_obj_InfoType_parse(void **cursor, unsigned short len, struct wpp_InfoType *out);
extern void wpp_obj_Duration_encode(const struct wpp_Duration *obj, void **cursor);
extern int wpp_obj_Duration_parse(void **cursor, unsigned short len, struct wpp_Duration *out);
extern void wpp_obj_GlyphId_encode(const struct wpp_GlyphId *obj, void **cursor);
extern void wpp_obj_ImageMetadata_encode(const struct wpp_ImageMetadata *obj, void **cursor);
extern void wpp_obj_Version_encode(const struct wpp_Version *obj, void **cursor);
extern int wpp_obj_Version_parse(void **cursor, unsigned short len, struct wpp_Version *out);
extern void wpp_obj_NotificationAppInfo_encode(const struct wpp_NotificationAppInfo *obj, void **cursor);
extern void wpp_obj_NotificationAppId_encode(const struct wpp_NotificationAppId *obj, void **cursor);
extern void wpp_obj_NotificationAppHashIdVersion_encode(const struct wpp_NotificationAppHashIdVersion *obj, void **cursor);
extern void wpp_obj_NotificationAppHashIdCrc32_encode(const struct wpp_NotificationAppHashIdCrc32 *obj, void **cursor);
extern int wpp_obj_CacheType_parse(void **cursor, unsigned short len, struct wpp_CacheType *out);
extern void wpp_obj_ActivitySubcategory_encode(const struct wpp_ActivitySubcategory *obj, void **cursor);
extern void wpp_obj_Timestamp_encode(const struct wpp_Timestamp *obj, void **cursor);
extern int wpp_obj_FwInfo_parse(void **cursor, unsigned short len, struct wpp_FwInfo *out);
extern void wpp_obj_FwChunkRequest_encode(const struct wpp_FwChunkRequest *obj, void **cursor);
extern void wpp_obj_StartTime_encode(const struct wpp_StartTime *obj, void **cursor);
extern void wpp_obj_EndTime_encode(const struct wpp_EndTime *obj, void **cursor);
extern void wpp_obj_Status_encode(const struct wpp_Status *obj, void **cursor);
extern int wpp_obj_TestScreen_parse(void **cursor, unsigned short len, struct wpp_TestScreen *out);
extern int wpp_obj_ChallengeRequest_parse(void **cursor, unsigned short len, struct wpp_ChallengeRequest *out);
extern void wpp_obj_DebugDumpAnchor_encode(const struct wpp_DebugDumpAnchor *obj, void **cursor);
extern void wpp_obj_FactoryMode_encode(const struct wpp_FactoryMode *obj, void **cursor);
extern int wpp_obj_FactoryMode_parse(void **cursor, unsigned short len, struct wpp_FactoryMode *out);
extern void wpp_obj_GlanceStatus_encode(const struct wpp_GlanceStatus *obj, void **cursor);
extern int wpp_obj_GlanceStatus_parse(void **cursor, unsigned short len, struct wpp_GlanceStatus *out);
extern void wpp_obj_MeasureCategory_encode(const struct wpp_MeasureCategory *obj, void **cursor);
extern void wpp_obj_MeasureLiveMeta_encode(const struct wpp_MeasureLiveMeta *obj, void **cursor);
extern void wpp_obj_MeasureLiveEcg_encode(const struct wpp_MeasureLiveEcg *obj, void **cursor);
extern void wpp_obj_MeasureStopReason_encode(const struct wpp_MeasureStopReason *obj, void **cursor);
extern void wpp_obj_PressureTemperature_encode(const struct wpp_PressureTemperature *obj, void **cursor);
extern int wpp_obj_AltimeterCompensation_parse(void **cursor, unsigned short len, struct wpp_AltimeterCompensation *out);
extern void wpp_obj_ActivityLap_encode(const struct wpp_ActivityLap *obj, void **cursor);
extern void wpp_obj_ActivityPause_encode(const struct wpp_ActivityPause *obj, void **cursor);
extern void wpp_obj_PauseState_encode(const struct wpp_PauseState *obj, void **cursor);
extern void wpp_obj_RebootOptional_encode(const struct wpp_RebootOptional *obj, void **cursor);
extern int wpp_obj_RebootOptional_parse(void **cursor, unsigned short len, struct wpp_RebootOptional *out);
extern void wpp_obj_DigitalCrownMotionDelta_encode(const struct wpp_DigitalCrownMotionDelta *obj, void **cursor);
extern void wpp_obj_MtuWpp_encode(const struct wpp_MtuWpp *obj, void **cursor);
extern int wpp_obj_MtuWpp_parse(void **cursor, unsigned short len, struct wpp_MtuWpp *out);
extern void wpp_obj_MtuTls_encode(const struct wpp_MtuTls *obj, void **cursor);
extern void wpp_obj_MtuAttBle_encode(const struct wpp_MtuAttBle *obj, void **cursor);
extern void wpp_obj_Heartrate_encode(const struct wpp_Heartrate *obj, void **cursor);
extern void wpp_obj_VasistasSpo2_encode(const struct wpp_VasistasSpo2 *obj, void **cursor);
extern void wpp_obj_VasistasFlags_encode(const struct wpp_VasistasFlags *obj, void **cursor);
extern void wpp_obj_VasistasAhi_encode(const struct wpp_VasistasAhi *obj, void **cursor);
extern void wpp_obj_ShortcutAction_encode(const struct wpp_ShortcutAction *obj, void **cursor);
extern void wpp_obj_NotificationsDisplayState_encode(const struct wpp_NotificationsDisplayState *obj, void **cursor);
extern void wpp_obj_LocalNotification_encode(const struct wpp_LocalNotification *obj, void **cursor);
extern void wpp_obj_EventV2_encode(const struct wpp_EventV2 *obj, void **cursor);
extern void wpp_obj_Boolean_encode(const struct wpp_Boolean *obj, void **cursor);
extern int wpp_obj_Boolean_parse(void **cursor, unsigned short len, struct wpp_Boolean *out);
extern void wpp_obj_InactivityCfg_encode(const struct wpp_InactivityCfg *obj, void **cursor);
extern void wpp_obj_AlgoParam_encode(const struct wpp_AlgoParam *obj, void **cursor);
extern void wpp_obj_Stairs_encode(const struct wpp_Stairs *obj, void **cursor);
extern int wpp_obj_Stairs_parse(void **cursor, unsigned short len, struct wpp_Stairs *out);
extern void wpp_obj_MoveHands_encode(const struct wpp_MoveHands *obj, void **cursor);
extern int wpp_obj_MoveHands_parse(void **cursor, unsigned short len, struct wpp_MoveHands *out);
extern void wpp_obj_WorkoutMaxNumber_encode(const struct wpp_WorkoutMaxNumber *obj, void **cursor);
extern void wpp_obj_SkinTemperatureMeasureResult_encode(const struct wpp_SkinTemperatureMeasureResult *obj, void **cursor);
extern void wpp_obj_FluxSensorMeasureResult_encode(const struct wpp_FluxSensorMeasureResult *obj, void **cursor);
extern int wpp_obj_DeviceChallengeRequest_parse(void **cursor, unsigned short len, struct wpp_DeviceChallengeRequest *out);
extern void wpp_obj_DeviceChallengeReply_encode(const struct wpp_DeviceChallengeReply *obj, void **cursor);
extern void wpp_obj_DeviceChallengeSignature_encode(const struct wpp_DeviceChallengeSignature *obj, void **cursor);
extern void wpp_obj_FactoryTestDsc_encode(const struct wpp_FactoryTestDsc *obj, void **cursor);
extern int wpp_obj_FactoryTestDsc_parse(void **cursor, unsigned short len, struct wpp_FactoryTestDsc *out);
extern void wpp_obj_VasistasCbt_encode(const struct wpp_VasistasCbt *obj, void **cursor);
extern void wpp_obj_Max86173ChannelStats_encode(const struct wpp_Max86173ChannelStats *obj, void **cursor);
extern void wpp_obj_GreentegSensitivityBin_encode(const struct wpp_GreentegSensitivityBin *obj, void **cursor);
extern int wpp_obj_GreentegSensitivityBin_parse(void **cursor, unsigned short len, struct wpp_GreentegSensitivityBin *out);
extern void wpp_obj_DigitalCrownScaleFactor_encode(const struct wpp_DigitalCrownScaleFactor *obj, void **cursor);
extern int wpp_obj_DigitalCrownScaleFactor_parse(void **cursor, unsigned short len, struct wpp_DigitalCrownScaleFactor *out);
extern int wpp_obj_SymptomType_parse(void **cursor, unsigned short len, struct wpp_SymptomType *out);
extern void wpp_obj_SymptomListItem_encode(const struct wpp_SymptomListItem *obj, void **cursor);
extern int wpp_obj_VibratorSetSimple_parse(void **cursor, unsigned short len, struct wpp_VibratorSetSimple *out);
extern void wpp_obj_CycleTrackingMenstruationStart_encode(const struct wpp_CycleTrackingMenstruationStart *obj, void **cursor);
extern void wpp_obj_GreentegIntegrationFactor_encode(const struct wpp_GreentegIntegrationFactor *obj, void **cursor);
extern int wpp_obj_GreentegIntegrationFactor_parse(void **cursor, unsigned short len, struct wpp_GreentegIntegrationFactor *out);
extern void wpp_obj_VasistasHrv_encode(const struct wpp_VasistasHrv *obj, void **cursor);
extern void wpp_obj_VasistasRr_encode(const struct wpp_VasistasRr *obj, void **cursor);
extern void wpp_obj_VasistasDbt_encode(const struct wpp_VasistasDbt *obj, void **cursor);

/* reply sizers: the byte count the object's reply carries, a
   `movs r0, #N; bx lr` stub, handed to the send path in r2
   alongside the encoder in r3. */
extern int wpp_obj_ActivitySubcategory_size(const void *obj);
extern int wpp_obj_Alarm_size(const void *obj);
extern int wpp_obj_AlarmEnabled_size(const void *obj);
extern int wpp_obj_AlgoParam_size(const void *obj);
extern int wpp_obj_AlgorithmVersion_size(const void *obj);
extern int wpp_obj_AncsStatus_size(const void *obj);
extern int wpp_obj_BatteryPercent_size(const void *obj);
extern int wpp_obj_BatteryStatus_size(const void *obj);
extern int wpp_obj_BatteryVoltageMv_size(const void *obj);
extern int wpp_obj_Boolean_size(const void *obj);
extern int wpp_obj_Calories_size(const void *obj);
extern int wpp_obj_Cmderror_size(const void *obj);
extern int wpp_obj_ConnectReason_size(const void *obj);
extern int wpp_obj_CustomizationIdGet_size(const void *obj);
extern int wpp_obj_CycleTrackingMenstruationStart_size(const void *obj);
extern int wpp_obj_DebugDumpAnchor_size(const void *obj);
extern int wpp_obj_DebugDumpData_size(const void *obj);
extern int wpp_obj_DebugDumpIgnoreData_size(const void *obj);
extern int wpp_obj_DebugDumpType_size(const void *obj);
extern int wpp_obj_DeviceChallengeReply_size(const void *obj);
extern int wpp_obj_DigitalCrownMotionDelta_size(const void *obj);
extern int wpp_obj_Distance_size(const void *obj);
extern int wpp_obj_Duration_size(const void *obj);
extern int wpp_obj_EndTime_size(const void *obj);
extern int wpp_obj_EventV2_size(const void *obj);
extern int wpp_obj_FactoryMode_size(const void *obj);
extern int wpp_obj_FactoryState_size(const void *obj);
extern int wpp_obj_FactoryTestDsc_size(const void *obj);
extern int wpp_obj_FeatureMask_size(const void *obj);
extern int wpp_obj_FirmwareVersion_size(const void *obj);
extern int wpp_obj_FluxSensorMeasureResult_size(const void *obj);
extern int wpp_obj_FwChunkRequest_size(const void *obj);
extern int wpp_obj_GlanceStatus_size(const void *obj);
extern int wpp_obj_Gpio_size(const void *obj);
extern int wpp_obj_GreentegIntegrationFactor_size(const void *obj);
extern int wpp_obj_GreentegSensitivityBin_size(const void *obj);
extern int wpp_obj_Heartrate_size(const void *obj);
extern int wpp_obj_HrAutoAlgo_size(const void *obj);
extern int wpp_obj_Id_size(const void *obj);
extern int wpp_obj_ImageMetadata_size(const void *obj);
extern int wpp_obj_InactivityCfg_size(const void *obj);
extern int wpp_obj_Int32_size(const void *obj);
extern int wpp_obj_LightSensorReply_size(const void *obj);
extern int wpp_obj_LiveHr_size(const void *obj);
extern int wpp_obj_LocaleSet_size(const void *obj);
extern int wpp_obj_LuminosityLevel_size(const void *obj);
extern int wpp_obj_Mac_size(const void *obj);
extern int wpp_obj_McuId_size(const void *obj);
extern int wpp_obj_MeasureCategory_size(const void *obj);
extern int wpp_obj_MeasureLiveMeta_size(const void *obj);
extern int wpp_obj_MeasureStopReason_size(const void *obj);
extern int wpp_obj_MoveHands_size(const void *obj);
extern int wpp_obj_MtuAttBle_size(const void *obj);
extern int wpp_obj_MtuTls_size(const void *obj);
extern int wpp_obj_MtuWpp_size(const void *obj);
extern int wpp_obj_Name_size(const void *obj);
extern int wpp_obj_NbAlarm_size(const void *obj);
extern int wpp_obj_NotificationAppHashIdCrc32_size(const void *obj);
extern int wpp_obj_NotificationAppHashIdVersion_size(const void *obj);
extern int wpp_obj_NotificationAppId_size(const void *obj);
extern int wpp_obj_NotificationAppInfo_size(const void *obj);
extern int wpp_obj_NotificationsDisplayState_size(const void *obj);
extern int wpp_obj_Null_size(const void *obj);
extern int wpp_obj_PauseState_size(const void *obj);
extern int wpp_obj_PlsReturnCode_size(const void *obj);
extern int wpp_obj_PlsStation_size(const void *obj);
extern int wpp_obj_PressureTemperature_size(const void *obj);
extern int wpp_obj_ProbeChallenge_size(const void *obj);
extern int wpp_obj_ProbeChallengeResponse_size(const void *obj);
extern int wpp_obj_RebootOptional_size(const void *obj);
extern int wpp_obj_ReturnCode_size(const void *obj);
extern int wpp_obj_ShortcutAction_size(const void *obj);
extern int wpp_obj_SkinTemperatureMeasureResult_size(const void *obj);
extern int wpp_obj_SoftdeviceVersion_size(const void *obj);
extern int wpp_obj_Stairs_size(const void *obj);
extern int wpp_obj_StartTime_size(const void *obj);
extern int wpp_obj_Status_size(const void *obj);
extern int wpp_obj_Steps_size(const void *obj);
extern int wpp_obj_StoredMeasureData_size(const void *obj);
extern int wpp_obj_StoredMeasureMeta_size(const void *obj);
extern int wpp_obj_StoredSignalData_size(const void *obj);
extern int wpp_obj_StoredSignalMeta_size(const void *obj);
extern int wpp_obj_StoredSignalMetaExtend_size(const void *obj);
extern int wpp_obj_SymptomListItem_size(const void *obj);
extern int wpp_obj_SyncRequest_size(const void *obj);
extern int wpp_obj_TempCalReply_size(const void *obj);
extern int wpp_obj_TimeSet_size(const void *obj);
extern int wpp_obj_TimeSetReply_size(const void *obj);
extern int wpp_obj_Timestamp_size(const void *obj);
extern int wpp_obj_TrackerUser_size(const void *obj);
extern int wpp_obj_TrackerWearPos_size(const void *obj);
extern int wpp_obj_Uint32_size(const void *obj);
extern int wpp_obj_UnitConversionParameters_size(const void *obj);
extern int wpp_obj_UnknownSteps_size(const void *obj);
extern int wpp_obj_VasistasActiRecoV1V2_size(const void *obj);
extern int wpp_obj_VasistasHeartrate_size(const void *obj);
extern int wpp_obj_VasistasSwimType_size(const void *obj);
extern int wpp_obj_Version_size(const void *obj);
extern int wpp_obj_WamDailyActivities_size(const void *obj);
extern int wpp_obj_WamScreensList_size(const void *obj);
extern int wpp_obj_WamVasistasAwake_size(const void *obj);
extern int wpp_obj_WamVasistasDuration_size(const void *obj);
extern int wpp_obj_WamVasistasHead_size(const void *obj);
extern int wpp_obj_WamVasistasMetCalEarned_size(const void *obj);
extern int wpp_obj_WamVasistasRun_size(const void *obj);
extern int wpp_obj_WamVasistasSleep_size(const void *obj);
extern int wpp_obj_WamVasistasWalk_size(const void *obj);
extern int wpp_obj_WorkoutMaxNumber_size(const void *obj);
extern int wpp_obj_WorkoutScreenList_size(const void *obj);
extern int wpp_obj_WppString_size(const void *obj);

/* typed send path: one inline wrapper per object type the image both
   sizes and encodes, over wpp_send_object_alias's erased pair. */
static inline void wpp_send_Null(unsigned short command, const struct wpp_Null *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Null_size,
                          (wpp_obj_encoder)wpp_obj_Null_encode);
}
static inline void wpp_send_BatteryPercent(unsigned short command, const struct wpp_BatteryPercent *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_BatteryPercent_size,
                          (wpp_obj_encoder)wpp_obj_BatteryPercent_encode);
}
static inline void wpp_send_Cmderror(unsigned short command, const struct wpp_Cmderror *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Cmderror_size,
                          (wpp_obj_encoder)wpp_obj_Cmderror_encode);
}
static inline void wpp_send_StoredMeasureMeta(unsigned short command, const struct wpp_StoredMeasureMeta *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StoredMeasureMeta_size,
                          (wpp_obj_encoder)wpp_obj_StoredMeasureMeta_encode);
}
static inline void wpp_send_StoredMeasureData(unsigned short command, const struct wpp_StoredMeasureData *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StoredMeasureData_size,
                          (wpp_obj_encoder)wpp_obj_StoredMeasureData_encode);
}
static inline void wpp_send_ConnectReason(unsigned short command, const struct wpp_ConnectReason *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ConnectReason_size,
                          (wpp_obj_encoder)wpp_obj_ConnectReason_encode);
}
static inline void wpp_send_DebugDumpData(unsigned short command, const struct wpp_DebugDumpData *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DebugDumpData_size,
                          (wpp_obj_encoder)wpp_obj_DebugDumpData_encode);
}
static inline void wpp_send_DebugDumpType(unsigned short command, const struct wpp_DebugDumpType *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DebugDumpType_size,
                          (wpp_obj_encoder)wpp_obj_DebugDumpType_encode);
}
static inline void wpp_send_LocaleSet(unsigned short command, const struct wpp_LocaleSet *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_LocaleSet_size,
                          (wpp_obj_encoder)wpp_obj_LocaleSet_encode);
}
static inline void wpp_send_ProbeChallenge(unsigned short command, const struct wpp_ProbeChallenge *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ProbeChallenge_size,
                          (wpp_obj_encoder)wpp_obj_ProbeChallenge_encode);
}
static inline void wpp_send_ProbeChallengeResponse(unsigned short command, const struct wpp_ProbeChallengeResponse *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ProbeChallengeResponse_size,
                          (wpp_obj_encoder)wpp_obj_ProbeChallengeResponse_encode);
}
static inline void wpp_send_BatteryVoltageMv(unsigned short command, const struct wpp_BatteryVoltageMv *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_BatteryVoltageMv_size,
                          (wpp_obj_encoder)wpp_obj_BatteryVoltageMv_encode);
}
static inline void wpp_send_DebugDumpIgnoreData(unsigned short command, const struct wpp_DebugDumpIgnoreData *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DebugDumpIgnoreData_size,
                          (wpp_obj_encoder)wpp_obj_DebugDumpIgnoreData_encode);
}
static inline void wpp_send_NbAlarm(unsigned short command, const struct wpp_NbAlarm *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NbAlarm_size,
                          (wpp_obj_encoder)wpp_obj_NbAlarm_encode);
}
static inline void wpp_send_PlsReturnCode(unsigned short command, const struct wpp_PlsReturnCode *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_PlsReturnCode_size,
                          (wpp_obj_encoder)wpp_obj_PlsReturnCode_encode);
}
static inline void wpp_send_PlsStation(unsigned short command, const struct wpp_PlsStation *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_PlsStation_size,
                          (wpp_obj_encoder)wpp_obj_PlsStation_encode);
}
static inline void wpp_send_FactoryState(unsigned short command, const struct wpp_FactoryState *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FactoryState_size,
                          (wpp_obj_encoder)wpp_obj_FactoryState_encode);
}
static inline void wpp_send_TrackerWearPos(unsigned short command, const struct wpp_TrackerWearPos *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_TrackerWearPos_size,
                          (wpp_obj_encoder)wpp_obj_TrackerWearPos_encode);
}
static inline void wpp_send_FeatureMask(unsigned short command, const struct wpp_FeatureMask *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FeatureMask_size,
                          (wpp_obj_encoder)wpp_obj_FeatureMask_encode);
}
static inline void wpp_send_McuId(unsigned short command, const struct wpp_McuId *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_McuId_size,
                          (wpp_obj_encoder)wpp_obj_McuId_encode);
}
static inline void wpp_send_SoftdeviceVersion(unsigned short command, const struct wpp_SoftdeviceVersion *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_SoftdeviceVersion_size,
                          (wpp_obj_encoder)wpp_obj_SoftdeviceVersion_encode);
}
static inline void wpp_send_HrAutoAlgo(unsigned short command, const struct wpp_HrAutoAlgo *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_HrAutoAlgo_size,
                          (wpp_obj_encoder)wpp_obj_HrAutoAlgo_encode);
}
static inline void wpp_send_WorkoutScreenList(unsigned short command, const struct wpp_WorkoutScreenList *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WorkoutScreenList_size,
                          (wpp_obj_encoder)wpp_obj_WorkoutScreenList_encode);
}
static inline void wpp_send_SyncRequest(unsigned short command, const struct wpp_SyncRequest *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_SyncRequest_size,
                          (wpp_obj_encoder)wpp_obj_SyncRequest_encode);
}
static inline void wpp_send_StoredSignalMeta(unsigned short command, const struct wpp_StoredSignalMeta *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StoredSignalMeta_size,
                          (wpp_obj_encoder)wpp_obj_StoredSignalMeta_encode);
}
static inline void wpp_send_StoredSignalData(unsigned short command, const struct wpp_StoredSignalData *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StoredSignalData_size,
                          (wpp_obj_encoder)wpp_obj_StoredSignalData_encode);
}
static inline void wpp_send_Id(unsigned short command, const struct wpp_Id *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Id_size,
                          (wpp_obj_encoder)wpp_obj_Id_encode);
}
static inline void wpp_send_StoredSignalMetaExtend(unsigned short command, const struct wpp_StoredSignalMetaExtend *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StoredSignalMetaExtend_size,
                          (wpp_obj_encoder)wpp_obj_StoredSignalMetaExtend_encode);
}
static inline void wpp_send_UnitConversionParameters(unsigned short command, const struct wpp_UnitConversionParameters *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_UnitConversionParameters_size,
                          (wpp_obj_encoder)wpp_obj_UnitConversionParameters_encode);
}
static inline void wpp_send_AlgorithmVersion(unsigned short command, const struct wpp_AlgorithmVersion *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_AlgorithmVersion_size,
                          (wpp_obj_encoder)wpp_obj_AlgorithmVersion_encode);
}
static inline void wpp_send_FirmwareVersion(unsigned short command, const struct wpp_FirmwareVersion *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FirmwareVersion_size,
                          (wpp_obj_encoder)wpp_obj_FirmwareVersion_encode);
}
static inline void wpp_send_Gpio(unsigned short command, const struct wpp_Gpio *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Gpio_size,
                          (wpp_obj_encoder)wpp_obj_Gpio_encode);
}
static inline void wpp_send_Uint32(unsigned short command, const struct wpp_Uint32 *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Uint32_size,
                          (wpp_obj_encoder)wpp_obj_Uint32_encode);
}
static inline void wpp_send_WppString(unsigned short command, const struct wpp_WppString *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WppString_size,
                          (wpp_obj_encoder)wpp_obj_WppString_encode);
}
static inline void wpp_send_Int32(unsigned short command, const struct wpp_Int32 *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Int32_size,
                          (wpp_obj_encoder)wpp_obj_Int32_encode);
}
static inline void wpp_send_Mac(unsigned short command, const struct wpp_Mac *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Mac_size,
                          (wpp_obj_encoder)wpp_obj_Mac_encode);
}
static inline void wpp_send_TimeSet(unsigned short command, const struct wpp_TimeSet *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_TimeSet_size,
                          (wpp_obj_encoder)wpp_obj_TimeSet_encode);
}
static inline void wpp_send_TimeSetReply(unsigned short command, const struct wpp_TimeSetReply *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_TimeSetReply_size,
                          (wpp_obj_encoder)wpp_obj_TimeSetReply_encode);
}
static inline void wpp_send_TrackerUser(unsigned short command, const struct wpp_TrackerUser *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_TrackerUser_size,
                          (wpp_obj_encoder)wpp_obj_TrackerUser_encode);
}
static inline void wpp_send_BatteryStatus(unsigned short command, const struct wpp_BatteryStatus *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_BatteryStatus_size,
                          (wpp_obj_encoder)wpp_obj_BatteryStatus_encode);
}
static inline void wpp_send_WamDailyActivities(unsigned short command, const struct wpp_WamDailyActivities *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamDailyActivities_size,
                          (wpp_obj_encoder)wpp_obj_WamDailyActivities_encode);
}
static inline void wpp_send_WamScreensList(unsigned short command, const struct wpp_WamScreensList *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamScreensList_size,
                          (wpp_obj_encoder)wpp_obj_WamScreensList_encode);
}
static inline void wpp_send_Alarm(unsigned short command, const struct wpp_Alarm *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Alarm_size,
                          (wpp_obj_encoder)wpp_obj_Alarm_encode);
}
static inline void wpp_send_Name(unsigned short command, const struct wpp_Name *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Name_size,
                          (wpp_obj_encoder)wpp_obj_Name_encode);
}
static inline void wpp_send_WamVasistasHead(unsigned short command, const struct wpp_WamVasistasHead *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasHead_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasHead_encode);
}
static inline void wpp_send_WamVasistasDuration(unsigned short command, const struct wpp_WamVasistasDuration *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasDuration_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasDuration_encode);
}
static inline void wpp_send_WamVasistasAwake(unsigned short command, const struct wpp_WamVasistasAwake *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasAwake_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasAwake_encode);
}
static inline void wpp_send_WamVasistasWalk(unsigned short command, const struct wpp_WamVasistasWalk *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasWalk_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasWalk_encode);
}
static inline void wpp_send_WamVasistasRun(unsigned short command, const struct wpp_WamVasistasRun *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasRun_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasRun_encode);
}
static inline void wpp_send_WamVasistasSleep(unsigned short command, const struct wpp_WamVasistasSleep *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasSleep_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasSleep_encode);
}
static inline void wpp_send_WamVasistasMetCalEarned(unsigned short command, const struct wpp_WamVasistasMetCalEarned *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WamVasistasMetCalEarned_size,
                          (wpp_obj_encoder)wpp_obj_WamVasistasMetCalEarned_encode);
}
static inline void wpp_send_VasistasActiRecoV1V2(unsigned short command, const struct wpp_VasistasActiRecoV1V2 *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_VasistasActiRecoV1V2_size,
                          (wpp_obj_encoder)wpp_obj_VasistasActiRecoV1V2_encode);
}
static inline void wpp_send_VasistasSwimType(unsigned short command, const struct wpp_VasistasSwimType *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_VasistasSwimType_size,
                          (wpp_obj_encoder)wpp_obj_VasistasSwimType_encode);
}
static inline void wpp_send_ReturnCode(unsigned short command, const struct wpp_ReturnCode *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ReturnCode_size,
                          (wpp_obj_encoder)wpp_obj_ReturnCode_encode);
}
static inline void wpp_send_AlarmEnabled(unsigned short command, const struct wpp_AlarmEnabled *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_AlarmEnabled_size,
                          (wpp_obj_encoder)wpp_obj_AlarmEnabled_encode);
}
static inline void wpp_send_VasistasHeartrate(unsigned short command, const struct wpp_VasistasHeartrate *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_VasistasHeartrate_size,
                          (wpp_obj_encoder)wpp_obj_VasistasHeartrate_encode);
}
static inline void wpp_send_AncsStatus(unsigned short command, const struct wpp_AncsStatus *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_AncsStatus_size,
                          (wpp_obj_encoder)wpp_obj_AncsStatus_encode);
}
static inline void wpp_send_TempCalReply(unsigned short command, const struct wpp_TempCalReply *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_TempCalReply_size,
                          (wpp_obj_encoder)wpp_obj_TempCalReply_encode);
}
static inline void wpp_send_LightSensorReply(unsigned short command, const struct wpp_LightSensorReply *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_LightSensorReply_size,
                          (wpp_obj_encoder)wpp_obj_LightSensorReply_encode);
}
static inline void wpp_send_CustomizationIdGet(unsigned short command, const struct wpp_CustomizationIdGet *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_CustomizationIdGet_size,
                          (wpp_obj_encoder)wpp_obj_CustomizationIdGet_encode);
}
static inline void wpp_send_LuminosityLevel(unsigned short command, const struct wpp_LuminosityLevel *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_LuminosityLevel_size,
                          (wpp_obj_encoder)wpp_obj_LuminosityLevel_encode);
}
static inline void wpp_send_LiveHr(unsigned short command, const struct wpp_LiveHr *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_LiveHr_size,
                          (wpp_obj_encoder)wpp_obj_LiveHr_encode);
}
static inline void wpp_send_UnknownSteps(unsigned short command, const struct wpp_UnknownSteps *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_UnknownSteps_size,
                          (wpp_obj_encoder)wpp_obj_UnknownSteps_encode);
}
static inline void wpp_send_Steps(unsigned short command, const struct wpp_Steps *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Steps_size,
                          (wpp_obj_encoder)wpp_obj_Steps_encode);
}
static inline void wpp_send_Calories(unsigned short command, const struct wpp_Calories *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Calories_size,
                          (wpp_obj_encoder)wpp_obj_Calories_encode);
}
static inline void wpp_send_Distance(unsigned short command, const struct wpp_Distance *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Distance_size,
                          (wpp_obj_encoder)wpp_obj_Distance_encode);
}
static inline void wpp_send_Duration(unsigned short command, const struct wpp_Duration *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Duration_size,
                          (wpp_obj_encoder)wpp_obj_Duration_encode);
}
static inline void wpp_send_ImageMetadata(unsigned short command, const struct wpp_ImageMetadata *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ImageMetadata_size,
                          (wpp_obj_encoder)wpp_obj_ImageMetadata_encode);
}
static inline void wpp_send_Version(unsigned short command, const struct wpp_Version *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Version_size,
                          (wpp_obj_encoder)wpp_obj_Version_encode);
}
static inline void wpp_send_NotificationAppInfo(unsigned short command, const struct wpp_NotificationAppInfo *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NotificationAppInfo_size,
                          (wpp_obj_encoder)wpp_obj_NotificationAppInfo_encode);
}
static inline void wpp_send_NotificationAppId(unsigned short command, const struct wpp_NotificationAppId *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NotificationAppId_size,
                          (wpp_obj_encoder)wpp_obj_NotificationAppId_encode);
}
static inline void wpp_send_NotificationAppHashIdVersion(unsigned short command, const struct wpp_NotificationAppHashIdVersion *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NotificationAppHashIdVersion_size,
                          (wpp_obj_encoder)wpp_obj_NotificationAppHashIdVersion_encode);
}
static inline void wpp_send_NotificationAppHashIdCrc32(unsigned short command, const struct wpp_NotificationAppHashIdCrc32 *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NotificationAppHashIdCrc32_size,
                          (wpp_obj_encoder)wpp_obj_NotificationAppHashIdCrc32_encode);
}
static inline void wpp_send_ActivitySubcategory(unsigned short command, const struct wpp_ActivitySubcategory *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ActivitySubcategory_size,
                          (wpp_obj_encoder)wpp_obj_ActivitySubcategory_encode);
}
static inline void wpp_send_Timestamp(unsigned short command, const struct wpp_Timestamp *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Timestamp_size,
                          (wpp_obj_encoder)wpp_obj_Timestamp_encode);
}
static inline void wpp_send_FwChunkRequest(unsigned short command, const struct wpp_FwChunkRequest *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FwChunkRequest_size,
                          (wpp_obj_encoder)wpp_obj_FwChunkRequest_encode);
}
static inline void wpp_send_StartTime(unsigned short command, const struct wpp_StartTime *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_StartTime_size,
                          (wpp_obj_encoder)wpp_obj_StartTime_encode);
}
static inline void wpp_send_EndTime(unsigned short command, const struct wpp_EndTime *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_EndTime_size,
                          (wpp_obj_encoder)wpp_obj_EndTime_encode);
}
static inline void wpp_send_Status(unsigned short command, const struct wpp_Status *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Status_size,
                          (wpp_obj_encoder)wpp_obj_Status_encode);
}
static inline void wpp_send_DebugDumpAnchor(unsigned short command, const struct wpp_DebugDumpAnchor *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DebugDumpAnchor_size,
                          (wpp_obj_encoder)wpp_obj_DebugDumpAnchor_encode);
}
static inline void wpp_send_FactoryMode(unsigned short command, const struct wpp_FactoryMode *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FactoryMode_size,
                          (wpp_obj_encoder)wpp_obj_FactoryMode_encode);
}
static inline void wpp_send_GlanceStatus(unsigned short command, const struct wpp_GlanceStatus *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_GlanceStatus_size,
                          (wpp_obj_encoder)wpp_obj_GlanceStatus_encode);
}
static inline void wpp_send_MeasureCategory(unsigned short command, const struct wpp_MeasureCategory *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MeasureCategory_size,
                          (wpp_obj_encoder)wpp_obj_MeasureCategory_encode);
}
static inline void wpp_send_MeasureLiveMeta(unsigned short command, const struct wpp_MeasureLiveMeta *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MeasureLiveMeta_size,
                          (wpp_obj_encoder)wpp_obj_MeasureLiveMeta_encode);
}
static inline void wpp_send_MeasureStopReason(unsigned short command, const struct wpp_MeasureStopReason *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MeasureStopReason_size,
                          (wpp_obj_encoder)wpp_obj_MeasureStopReason_encode);
}
static inline void wpp_send_PressureTemperature(unsigned short command, const struct wpp_PressureTemperature *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_PressureTemperature_size,
                          (wpp_obj_encoder)wpp_obj_PressureTemperature_encode);
}
static inline void wpp_send_PauseState(unsigned short command, const struct wpp_PauseState *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_PauseState_size,
                          (wpp_obj_encoder)wpp_obj_PauseState_encode);
}
static inline void wpp_send_RebootOptional(unsigned short command, const struct wpp_RebootOptional *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_RebootOptional_size,
                          (wpp_obj_encoder)wpp_obj_RebootOptional_encode);
}
static inline void wpp_send_DigitalCrownMotionDelta(unsigned short command, const struct wpp_DigitalCrownMotionDelta *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DigitalCrownMotionDelta_size,
                          (wpp_obj_encoder)wpp_obj_DigitalCrownMotionDelta_encode);
}
static inline void wpp_send_MtuWpp(unsigned short command, const struct wpp_MtuWpp *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MtuWpp_size,
                          (wpp_obj_encoder)wpp_obj_MtuWpp_encode);
}
static inline void wpp_send_MtuTls(unsigned short command, const struct wpp_MtuTls *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MtuTls_size,
                          (wpp_obj_encoder)wpp_obj_MtuTls_encode);
}
static inline void wpp_send_MtuAttBle(unsigned short command, const struct wpp_MtuAttBle *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MtuAttBle_size,
                          (wpp_obj_encoder)wpp_obj_MtuAttBle_encode);
}
static inline void wpp_send_Heartrate(unsigned short command, const struct wpp_Heartrate *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Heartrate_size,
                          (wpp_obj_encoder)wpp_obj_Heartrate_encode);
}
static inline void wpp_send_ShortcutAction(unsigned short command, const struct wpp_ShortcutAction *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_ShortcutAction_size,
                          (wpp_obj_encoder)wpp_obj_ShortcutAction_encode);
}
static inline void wpp_send_NotificationsDisplayState(unsigned short command, const struct wpp_NotificationsDisplayState *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_NotificationsDisplayState_size,
                          (wpp_obj_encoder)wpp_obj_NotificationsDisplayState_encode);
}
static inline void wpp_send_EventV2(unsigned short command, const struct wpp_EventV2 *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_EventV2_size,
                          (wpp_obj_encoder)wpp_obj_EventV2_encode);
}
static inline void wpp_send_Boolean(unsigned short command, const struct wpp_Boolean *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Boolean_size,
                          (wpp_obj_encoder)wpp_obj_Boolean_encode);
}
static inline void wpp_send_InactivityCfg(unsigned short command, const struct wpp_InactivityCfg *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_InactivityCfg_size,
                          (wpp_obj_encoder)wpp_obj_InactivityCfg_encode);
}
static inline void wpp_send_AlgoParam(unsigned short command, const struct wpp_AlgoParam *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_AlgoParam_size,
                          (wpp_obj_encoder)wpp_obj_AlgoParam_encode);
}
static inline void wpp_send_Stairs(unsigned short command, const struct wpp_Stairs *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_Stairs_size,
                          (wpp_obj_encoder)wpp_obj_Stairs_encode);
}
static inline void wpp_send_MoveHands(unsigned short command, const struct wpp_MoveHands *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_MoveHands_size,
                          (wpp_obj_encoder)wpp_obj_MoveHands_encode);
}
static inline void wpp_send_WorkoutMaxNumber(unsigned short command, const struct wpp_WorkoutMaxNumber *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_WorkoutMaxNumber_size,
                          (wpp_obj_encoder)wpp_obj_WorkoutMaxNumber_encode);
}
static inline void wpp_send_SkinTemperatureMeasureResult(unsigned short command, const struct wpp_SkinTemperatureMeasureResult *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_SkinTemperatureMeasureResult_size,
                          (wpp_obj_encoder)wpp_obj_SkinTemperatureMeasureResult_encode);
}
static inline void wpp_send_FluxSensorMeasureResult(unsigned short command, const struct wpp_FluxSensorMeasureResult *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FluxSensorMeasureResult_size,
                          (wpp_obj_encoder)wpp_obj_FluxSensorMeasureResult_encode);
}
static inline void wpp_send_DeviceChallengeReply(unsigned short command, const struct wpp_DeviceChallengeReply *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_DeviceChallengeReply_size,
                          (wpp_obj_encoder)wpp_obj_DeviceChallengeReply_encode);
}
static inline void wpp_send_FactoryTestDsc(unsigned short command, const struct wpp_FactoryTestDsc *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_FactoryTestDsc_size,
                          (wpp_obj_encoder)wpp_obj_FactoryTestDsc_encode);
}
static inline void wpp_send_GreentegSensitivityBin(unsigned short command, const struct wpp_GreentegSensitivityBin *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_GreentegSensitivityBin_size,
                          (wpp_obj_encoder)wpp_obj_GreentegSensitivityBin_encode);
}
static inline void wpp_send_SymptomListItem(unsigned short command, const struct wpp_SymptomListItem *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_SymptomListItem_size,
                          (wpp_obj_encoder)wpp_obj_SymptomListItem_encode);
}
static inline void wpp_send_CycleTrackingMenstruationStart(unsigned short command, const struct wpp_CycleTrackingMenstruationStart *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_CycleTrackingMenstruationStart_size,
                          (wpp_obj_encoder)wpp_obj_CycleTrackingMenstruationStart_encode);
}
static inline void wpp_send_GreentegIntegrationFactor(unsigned short command, const struct wpp_GreentegIntegrationFactor *obj)
{
    wpp_send_object_alias(obj, command, wpp_obj_GreentegIntegrationFactor_size,
                          (wpp_obj_encoder)wpp_obj_GreentegIntegrationFactor_encode);
}

#endif
