#!/usr/bin/env python3
"""Emit the generated half of the `wpp` crate from the extracted IR."""
import argparse
import json
import os
import re
import subprocess
import sys

RUST_KEYWORDS = {
    'as', 'async', 'await', 'box', 'break', 'const', 'continue', 'crate', 'do',
    'dyn', 'else', 'enum', 'extern', 'false', 'final', 'fn', 'for', 'if',
    'impl', 'in', 'let', 'loop', 'macro', 'match', 'mod', 'move', 'mut',
    'override', 'priv', 'pub', 'ref', 'return', 'self', 'static', 'struct',
    'super', 'trait', 'true', 'try', 'type', 'typeof', 'unsafe', 'unsized',
    'use', 'virtual', 'where', 'while', 'yield',
}

# kind -> (rust type, byte size of one element, Reader method, Writer method)
SCALARS = {
    'i8': ('i8', 1), 'u8': ('u8', 1),
    'i16': ('i16', 2), 'u16': ('u16', 2),
    'i32': ('i32', 4), 'u32': ('u32', 4),
    'i64': ('i64', 8), 'u64': ('u64', 8),
}
ARRAYS = {
    'array_u8': ('u8', 1), 'array_i16': ('i16', 2), 'array_u16': ('u16', 2),
    'array_i32': ('i32', 4), 'array_u32': ('u32', 4),
}

HEADER = ('// @generated by tools/emit_rust.py from tools/wpp.json.\n'
          '// Source of truth is the Withings APK; edit the emitter, not this file.\n'
          '#![allow(clippy::all)]\n\n')


def snake(name):
    s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name)
    s = re.sub(r'(?<=[A-Z])(?=[A-Z][a-z])', '_', s)
    return s.lower()


def field_ident(name):
    s = snake(name)
    return 'r#' + s if s in RUST_KEYWORDS else s


def const_ident(field, value):
    ident = (snake(field) + '_' + value).upper()
    ident = re.sub(r'[^A-Z0-9_]', '_', ident)
    return '_' + ident if ident[0].isdigit() else ident


def const_value(kind, value):
    """Render a Java constant as a literal of the field's Rust type.

    Withings declares every constant as a Java `short`, so error codes on
    unsigned fields arrive negative; the wire carries their two's complement.
    """
    bits = SCALARS[kind][1] * 8
    wrapped = value & ((1 << bits) - 1)
    if kind.startswith('i') and wrapped >= (1 << (bits - 1)):
        wrapped -= 1 << bits
    return str(wrapped)


def rust_type(kind):
    if kind in SCALARS:
        return SCALARS[kind][0]
    if kind == 'string':
        return 'String'
    if kind == 'bytes':
        return 'Vec<u8>'
    return 'Vec<%s>' % ARRAYS[kind][0]


def read_expr(kind):
    if kind in SCALARS:
        return 'r.%s()?' % kind
    if kind == 'string':
        return 'r.string()?'
    if kind == 'bytes':
        return 'r.bytes()?'
    return 'r.array_%s()?' % ARRAYS[kind][0]


def write_stmt(kind, expr):
    if kind in SCALARS:
        return 'w.%s(%s);' % (kind, expr)
    if kind == 'string':
        return 'w.string(&%s);' % expr
    if kind == 'bytes':
        return 'w.bytes(&%s);' % expr
    return 'w.array_%s(&%s);' % (ARRAYS[kind][0], expr)


def size_terms(fields):
    """Split a struct's encoded size into a constant and dynamic terms."""
    fixed = 0
    dynamic = []
    for f in fields:
        ident = field_ident(f['name'])
        kind = f['kind']
        if kind in SCALARS:
            fixed += SCALARS[kind][1]
        elif kind in ('string', 'bytes'):
            fixed += 1
            dynamic.append('self.%s.len()' % ident)
        else:
            fixed += 1
            elem = ARRAYS[kind][1]
            term = 'self.%s.len()' % ident
            dynamic.append(term if elem == 1 else '%s * %d' % (term, elem))
    return fixed, dynamic


def emit_object(obj):
    cls = obj['class']
    fields = obj['fields']
    out = []

    out.append('#[derive(Debug, Clone, PartialEq, Default)]')
    out.append('pub struct %s {' % cls)
    for f in fields:
        out.append('    pub %s: %s,' % (field_ident(f['name']), rust_type(f['kind'])))
    out.append('}\n')

    consts = []
    seen = set()
    for fname, values in obj['enums'].items():
        kind = next(f['kind'] for f in fields if f['name'] == fname)
        for vname, val in sorted(values.items(), key=lambda kv: kv[1]):
            ident = const_ident(fname, vname)
            if ident in seen:
                continue
            seen.add(ident)
            consts.append('    pub const %s: %s = %s;'
                          % (ident, rust_type(kind), const_value(kind, val)))

    namers = []
    for fname, values in obj['enums'].items():
        kind = next(f['kind'] for f in fields if f['name'] == fname)
        ty = rust_type(kind)
        arms = []
        used = set()
        for vname, val in sorted(values.items(), key=lambda kv: kv[1]):
            literal = const_value(kind, val)
            if literal in used:
                continue
            used.add(literal)
            arms.append('            %s => Some("%s"),' % (literal, vname))
        namers.append('    pub fn %s_name(value: %s) -> Option<&\'static str> {'
                      % (snake(fname), ty))
        namers.append('        match value {')
        namers.extend(arms)
        namers.append('            _ => None,')
        namers.append('        }')
        namers.append('    }')

    if consts or namers or obj['limits']:
        out.append('impl %s {' % cls)
        out.extend(consts)
        for lname, lval in obj['limits'].items():
            ident = re.sub(r'[^A-Z0-9_]', '_', lname.upper())
            if ident not in seen:
                seen.add(ident)
                out.append('    pub const %s: u32 = %d;' % (ident, lval))
        if (consts or obj['limits']) and namers:
            out.append('')
        out.extend(namers)
        out.append('}\n')

    fixed, dynamic = size_terms(fields)
    declared = obj['data_size']
    computed = '%d + %s' % (fixed, ' + '.join(dynamic)) if dynamic else str(fixed)
    # A declared size larger than the fields can occupy is a maximum: the app
    # writes it as the object's size and zero-pads the remainder.
    pads = declared is not None and bool(dynamic)

    out.append('impl WppObjectCodec for %s {' % cls)
    out.append('    const TYPE_ID: u16 = %d;' % obj['id'])
    out.append('    const TYPE_NAME: &\'static str = "%s";' % (obj['type_name'] or cls))
    out.append('    const CLASS_NAME: &\'static str = "%s";' % cls)
    out.append('    const FIXED_DATA_SIZE: Option<usize> = %s;'
               % ('Some(%d)' % declared if declared is not None else 'None'))
    out.append('')
    out.append('    fn data_size(&self) -> usize {')
    if pads:
        out.append('        core::cmp::max(%s, %d)' % (computed, declared))
    else:
        out.append('        %s' % computed)
    out.append('    }')
    out.append('')
    if fields:
        out.append('    fn parse(r: &mut Reader<\'_>) -> Result<Self, ParseError> {')
        out.append('        Ok(Self {')
        for f in fields:
            out.append('            %s: %s,' % (field_ident(f['name']), read_expr(f['kind'])))
        out.append('        })')
        out.append('    }')
        out.append('')
        out.append('    fn write(&self, w: &mut Writer) {')
        if pads:
            out.append('        let start = w.len();')
        for f in fields:
            out.append('        %s' % write_stmt(f['kind'], 'self.%s' % field_ident(f['name'])))
        if pads:
            out.append('        w.pad_to(start + self.data_size());')
        out.append('    }')
    else:
        out.append('    fn parse(_r: &mut Reader<\'_>) -> Result<Self, ParseError> {')
        out.append('        Ok(Self {})')
        out.append('    }')
        out.append('')
        out.append('    fn write(&self, _w: &mut Writer) {}')
    out.append('}\n')
    return '\n'.join(out)


def emit_objects(ir):
    objs = ir['objects']
    parts = [HEADER,
             'use crate::codec::{parse_object, ParseError, Reader, Writer, WppObjectCodec};\n\n']
    for obj in objs:
        parts.append(emit_object(obj))
        parts.append('\n')

    parts.append('/// Every object type the Withings app knows how to decode.\n')
    parts.append('#[derive(Debug, Clone, PartialEq)]\n')
    parts.append('pub enum WppObject {\n')
    for obj in objs:
        parts.append('    %s(%s),\n' % (obj['class'], obj['class']))
    parts.append('    /// A type id absent from the app\'s own dispatch table.\n')
    parts.append('    Unknown { type_id: u16, data: Vec<u8> },\n')
    parts.append('    /// A known type id whose payload did not match the extracted layout.\n')
    parts.append('    Malformed { type_id: u16, data: Vec<u8>, error: ParseError },\n')
    parts.append('}\n\n')

    parts.append('impl WppObject {\n')

    parts.append('    pub fn parse(type_id: u16, data: &[u8]) -> Self {\n')
    parts.append('        let parsed = match type_id {\n')
    for obj in objs:
        parts.append('            %d => parse_object::<%s>(data).map(WppObject::%s),\n'
                     % (obj['id'], obj['class'], obj['class']))
    parts.append('            _ => return WppObject::Unknown { type_id, data: data.to_vec() },\n')
    parts.append('        };\n')
    parts.append('        match parsed {\n')
    parts.append('            Ok(object) => object,\n')
    parts.append('            Err(error) => WppObject::Malformed { type_id, data: data.to_vec(), error },\n')
    parts.append('        }\n')
    parts.append('    }\n\n')

    def dispatch(name, sig, binding, body_known, body_unknown, body_malformed):
        parts.append('    pub fn %s%s {\n' % (name, sig))
        parts.append('        match self {\n')
        for obj in objs:
            parts.append('            WppObject::%s(%s) => %s,\n'
                         % (obj['class'], binding, body_known % obj))
        parts.append('            %s\n' % body_unknown)
        parts.append('            %s\n' % body_malformed)
        parts.append('        }\n')
        parts.append('    }\n\n')

    dispatch('type_id', '(&self) -> u16', '_',
             '%(id)d',
             'WppObject::Unknown { type_id, .. } => *type_id,',
             'WppObject::Malformed { type_id, .. } => *type_id,')
    dispatch('type_name', "(&self) -> &'static str", '_',
             '"%(type_name)s"',
             'WppObject::Unknown { .. } => "UNKNOWN",',
             'WppObject::Malformed { .. } => "MALFORMED",')
    dispatch('class_name', "(&self) -> &'static str", '_',
             '"%(class)s"',
             'WppObject::Unknown { .. } => "Unknown",',
             'WppObject::Malformed { .. } => "Malformed",')
    dispatch('data_size', '(&self) -> usize', 'o',
             'o.data_size()',
             'WppObject::Unknown { data, .. } => data.len(),',
             'WppObject::Malformed { data, .. } => data.len(),')

    parts.append('    pub fn write_data(&self, w: &mut Writer) {\n')
    parts.append('        match self {\n')
    for obj in objs:
        parts.append('            WppObject::%s(o) => o.write(w),\n' % obj['class'])
    parts.append('            WppObject::Unknown { data, .. } => w.raw(data),\n')
    parts.append('            WppObject::Malformed { data, .. } => w.raw(data),\n')
    parts.append('        }\n')
    parts.append('    }\n')
    parts.append('}\n\n')

    parts.append('/// Names for type ids the app declares but has no object class for.\n')
    parts.append('pub fn type_name_for_id(type_id: u16) -> Option<&\'static str> {\n')
    parts.append('    match type_id {\n')
    known = {o['id'] for o in objs}
    for tid, name in sorted(ir['type_names'].items(), key=lambda kv: int(kv[0])):
        if int(tid) not in known:
            parts.append('        %s => Some("%s"),\n' % (tid, name))
    parts.append('        _ => None,\n')
    parts.append('    }\n')
    parts.append('}\n')
    return ''.join(parts)


def emit_commands(ir):
    parts = [HEADER]
    parts.append('/// A WPP command id, including its channel bits.\n')
    parts.append('#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n')
    parts.append('pub struct Command(pub u16);\n\n')
    parts.append('impl Command {\n')
    seen = set()
    for cid, name in sorted(ir['commands'].items(), key=lambda kv: int(kv[0])):
        if name in seen:
            continue
        seen.add(name)
        parts.append('    pub const %s: Command = Command(%s);\n' % (name, cid))
    parts.append('\n')
    parts.append('    pub fn name(&self) -> Option<&\'static str> {\n')
    parts.append('        match self.0 {\n')
    for cid, name in sorted(ir['commands'].items(), key=lambda kv: int(kv[0])):
        parts.append('            %s => Some("%s"),\n' % (cid, name))
    parts.append('            _ => None,\n')
    parts.append('        }\n')
    parts.append('    }\n')
    parts.append('}\n\n')
    parts.append('impl core::fmt::Display for Command {\n')
    parts.append('    fn fmt(&self, f: &mut core::fmt::Formatter<\'_>) -> core::fmt::Result {\n')
    parts.append('        match self.name() {\n')
    parts.append('            Some(name) => write!(f, "{} (0x{:04x})", name, self.0),\n')
    parts.append('            None => write!(f, "UNKNOWN (0x{:04x})", self.0),\n')
    parts.append('        }\n')
    parts.append('    }\n')
    parts.append('}\n')
    return ''.join(parts)


def sample_value(kind, index):
    """A distinguishable non-default value, kept small enough for i8/u8."""
    n = (index % 100) + 1
    if kind in SCALARS:
        return '%d' % n
    if kind == 'string':
        return 'String::from("wpp%d")' % n
    return 'vec![%d, %d]' % (n, n + 1)


def emit_roundtrip_tests(ir):
    """Assert the emitted size arithmetic agrees with the APK's getDataSize()."""
    parts = [HEADER, 'use crate::codec::WppObjectCodec;\n',
             'use crate::objects::*;\n\n']
    parts.append('#[test]\n')
    parts.append('fn default_data_size_matches_apk() {\n')
    for obj in ir['objects']:
        if obj['data_size'] is None:
            continue
        parts.append('    assert_eq!(%s::default().data_size(), %d, "%s");\n'
                     % (obj['class'], obj['data_size'], obj['class']))
    parts.append('}\n\n')

    parts.append('/// Encode a populated instance of every type and decode it back, so the\n')
    parts.append('/// length-prefixed and zero-padded paths are exercised rather than the\n')
    parts.append('/// all-empty default.\n')
    parts.append('#[test]\n')
    parts.append('fn every_type_id_round_trips_through_the_enum() {\n')
    for obj in ir['objects']:
        parts.append('    {\n')
        parts.append('        let o = WppObject::%s(%s {\n' % (obj['class'], obj['class']))
        for i, f in enumerate(obj['fields']):
            parts.append('            %s: %s,\n' % (field_ident(f['name']), sample_value(f['kind'], i)))
        parts.append('            ..Default::default()\n')
        parts.append('        });\n')
        parts.append('        let mut w = crate::codec::Writer::new();\n')
        parts.append('        o.write_data(&mut w);\n')
        parts.append('        let bytes = w.finish();\n')
        parts.append('        assert_eq!(bytes.len(), o.data_size(), "%s size");\n' % obj['class'])
        parts.append('        assert_eq!(WppObject::parse(%d, &bytes), o, "%s round trip");\n'
                     % (obj['id'], obj['class']))
        parts.append('    }\n')
    parts.append('}\n')
    return ''.join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('ir', help='wpp.json produced by extract_wpp.py')
    ap.add_argument('-o', '--out-dir', required=True, help='crate src/ directory')
    args = ap.parse_args()

    ir = json.load(open(args.ir))
    targets = {
        'objects.rs': emit_objects(ir),
        'commands.rs': emit_commands(ir),
        'generated_tests.rs': emit_roundtrip_tests(ir),
    }
    written = []
    for name, text in targets.items():
        path = os.path.join(args.out_dir, name)
        with open(path, 'w') as fh:
            fh.write(text)
        written.append(path)
        print('%s: %d lines' % (path, text.count('\n')))

    # Format here so that regenerating is idempotent; otherwise rustfmt running
    # over the tree afterwards makes every later regeneration look like a diff.
    try:
        subprocess.run(['rustfmt', '--edition', '2021', *written], check=True)
    except FileNotFoundError:
        print('rustfmt not found; generated files left unformatted')
    except subprocess.CalledProcessError as err:
        sys.exit('rustfmt failed: %s' % err)


if __name__ == '__main__':
    main()
